### ISSUE TITLE
strategies/avx2/intra-avx2.c:1:0: sorry, unimplemented: 64-bit mode not compiled in

### ISSUE THREAD

**Issue by Selur** [ultravideo/kvazaar#110]
using https://github.com/jb-alvarado/media-autobuild_suite building kvazaar aborts, see: https://pastee.org/z76xk
and since it seemed like an issue that seemed to be source code related I thought I post it here

**Comment by wiiaboo** [comment]
Using bisect, the last working commit when compiling 32-bit is f7b6365. 64-bit is working fine.

**Comment by Arizer** [comment]
Thanks for the info. Should be fixed (d71f1b5). Let me know if there is still a problem.

**Comment by wiiaboo** [comment]
Looks fixed to me.
