### ISSUE TITLE
always get a undefined reference to `__imp_kvz_api_get_apiv8' in ffmpeg

### ISSUE THREAD

**Issue by mausalimi** [ultravideo/kvazaar#111]
hello,

not sure what i'm doing wrong, but i always get that error when i try to include libkvazaar in ffmpeg.
no matter if i use the x86 or x64 version.

i built kvazaar 0.7.1 with msys and that actually worked without errors.

any help?

thanks a lot. :)

**Comment by aryla** [comment]
If you are using the static Kvazaar library, you need to pass `--extra-cflags=-DKVZ_STATIC_LIB` to FFmpeg's configure script.

**Comment by mausalimi** [comment]
ah, that did the trick!

thanks, this can be deleted, as it's not a bug at all.
