### ISSUE TITLE
Question about library version

### ISSUE THREAD

**Issue by darealshinji** [ultravideo/kvazaar#112]
According to the [Makefile](https://github.com/ultravideo/kvazaar/blob/master/src/Makefile#L14) the current library version is 2.2.0, resulting in the library name `libkvazaar.so.2` on ELF systems and `libkvazaar.2.dylib` on OSX.
But in `src/kvazaar_version.h` the current public API is 9. Shouldn't that one be used on the shared library name instead?

**Comment by aryla** [comment]
We update the library version in `Makefile` on releases and the API version in `kvazaar_version.h` on commits. (Although I'm not sure how useful this is.)

**Comment by Venti-** [comment]
src/kvazaar_version.h has been removed. The only versions now are the lib version in configure.ac and the fancy version in global.h.

**Comment by darealshinji** [comment]
Though the file `src/kvazaar_version.h` is still present.

**Comment by Venti-** [comment]
I guess meaning to delete it doesn't actually do anything. Removed for real now.
