### ISSUE TITLE
Build without -fvisibility=hidden on Linux

### ISSUE THREAD

**Issue by darealshinji** [ultravideo/kvazaar#113]
I figured that linking the command line program against the shared library actually works if I build Kvazaar without `-fvisibility=hidden`. Just wanted to let you know.

**Comment by aryla** [comment]
There were a few functions not visible in the API that the command line program used. I moved them to encmain so it is now possible to link against the shared libraries even when built with `-fvisibility=hidden`.

**Comment by darealshinji** [comment]
Thanks. Now it works fine.
