### ISSUE TITLE
Building on OSX with clang

### ISSUE THREAD

**Issue by gaming-hacker** [ultravideo/kvazaar#115]
i did a git pull a few minutes and and when bulding i get this error

clang: warning: argument unused during compilation: '-pthread'

and make tests fail

../tests/speed_tests.c:109:10: error: expected ')'
      ++i, GET_TIME(&clock_now))
         ^
../tests/speed_tests.c:107:7: note: to match this '('
  for (unsigned i = 0; 
      ^
../tests/speed_tests.c:147:10: error: expected ')'
      ++i, GET_TIME(&clock_now))
         ^
../tests/speed_tests.c:145:7: note: to match this '('
  for (unsigned i = 0;
      ^
../tests/speed_tests.c:199:8: error: expected ')'
    ++i, GET_TIME(&clock_now))
       ^
../tests/speed_tests.c:197:7: note: to match this '('
  for (unsigned i = 0;
      ^

any help?

**Comment by Venti-** [comment]
At a glance it looks like mac version of our GET_TIME macro can't be used inside a for loop. Does the compilation and program work otherwise?

**Comment by gaming-hacker** [comment]
yes,  so far, so good but i've only just a basic function test.

the clang issue is probably because somewhere in the makefile where you link -pthread is not required ,clang requires -pthread when compiling but not when linking.

**Comment by gaming-hacker** [comment]
I did another pull and the pthread error has come up again.

clang: warning: argument unused during compilation: '-pthread'

i changed these lines in the makefile, i also compile with -O3 flags but no big deal, it now compiles without errors.

#moved pthreads to compiler flags
CFLAGS += -O3 -g -ftree-vectorize -pthread

#removed it from linking
LDFLAGS += -O3 -fvisibility=hidden -lm

**Comment by Venti-** [comment]
It seems Clang acts differently between Mac and Linux. It's Clangs problem and I'm not too worried about it sinse it doesn't seem to affect anything (pthread is still linked in, right?). If you come up with a pull request that fixes this issue and doesn't cause problems with gcc and Linux, we'll be glad to accept it, but I'll close this. Thanks for informing us though.

**Comment by gaming-hacker** [comment]
yes, pthread still linked.
