### ISSUE TITLE
linking  lib with ffmpeg:  pkg-config complains can't find it

### ISSUE THREAD

**Issue by gaming-hacker** [ultravideo/kvazaar#117]
i'm trying to link in the library to my ffmpeg build,
i've created .pc and .m

prefix=/usr/local
exec_prefix=${prefix}
libdir=/usr/locall/lib
incdir=${prefix}/include

Name: libkvazaar
Description: Open-source HEVC encoder
Version: 0.7.2
Libs: -L${libdir} -lkvazaar -lm 
Cflags: -I${incdir}

but pkg-config cannot find the library, did i miss something in the .pc file,  pkg-config points to the correct directory as other libraries build without issue

**Comment by gaming-hacker** [comment]
i find out why,  in the ffmpeg config it wants

enabled libkvazaar        && require_pkg_config "kvazaar < 0.7.0" kvazaar.h kvz_api_get

changed to

enabled libkvazaar        && require_pkg_config "kvazaar > 0.7.0" kvazaar.h kvz_api_get

and now compiles

**Comment by gaming-hacker** [comment]
spoke too soon, configure runs but will not compile

libavcodec/libkvazaar.c:176:82: error: too few arguments
      to function call, expected 7, have 5

ctx->api->encoder_encode(ctx->encoder, img_in, &data_out, &len_out, NULL)) {

**Comment by fador** [comment]
You seem to be using some older ffmpeg version, Kvazaar support is quite recent and the API was modified. There's a reason for that Kvazaar < 0.7.0 =)
https://trac.ffmpeg.org/ticket/4925
You can use new ffmpeg or old kvazaar to fix this.

**Comment by gaming-hacker** [comment]
I pull the most recent the version from the github on the 2.8 branch and unless the latest pull reverted back to the original branch???

my build is
ffmpeg version n2.8.1-16-gfcb8ee9

the patch is from 	Wed, 14 Oct 2015 
-enabled libkvazaar        && require_pkg_config kvazaar kvazaar.h kvz_api_get
+enabled libkvazaar        && require_pkg_config "kvazaar < 0.7.0" kvazaar.h kvz_api_get

"Maybe not the best way to fix a bug report by disabling feature, especially when git master is already ported to kvazaar >= 0.7"

**Comment by gaming-hacker** [comment]
i pulled from the main branch instead of 2.8 and builds without issue.
