### ISSUE TITLE
ABI changes without soname change

### ISSUE THREAD

**Issue by marillat** [ultravideo/kvazaar#120]
kvz_api_get_apiv8() has been renamed to kvz_api_get_apiv() and

````
mpv: symbol lookup error: /usr/lib/i386-linux-gnu/i686/cmov/libavcodec.so.56: undefined symbol: kvz_api_get_apiv8
ffplay: symbol lookup error: /usr/lib/i386-linux-gnu/i686/cmov/libavcodec.so.56: undefined symbol: kvz_api_get_apiv8
````

**Comment by Venti-** [comment]
What do you mean by it has been renamed?

I see that kvazaar.h was modified without incrementing KVZ_API_VERSION in kvazaar_version.h, but it's 10 not 8. The soname was however changed. If you know what we did wrong, please do tell so I can make a checklist for future API changes.

**Comment by marillat** [comment]
kvz_api_get_apiv8() doesn't exist in 0.8.1 I see only kvz_api_get_apiv()

**Comment by Venti-** [comment]
Could you tell a bit more about what you are doing? The only way I see the function being named kvz_api_get_apiv() instead of kvz_api_get_apiv10() is that the kvazaar_version.h is not in includes.

When I build with autotools and look at libkvazaar.so with objdump I see this:
0000000000018a60 g    DF .text  0000000000000008  Base        kvz_api_get_apiv10

**Comment by marillat** [comment]
I did a simple grep in the source. Bad idea.
Then you have changed  kvz_api_get_apiv8() to kvz_api_get_apiv10() but you have only incremented the minor soname  number to 4 (was 1 in 0.7.2) and this isn't enough.
In 0.8.1 the best was to increase  the major soname number to 3. So
in 0.7.2 ==> 2.1.0
in 0.8.1 ==> 2.4.0

0.8.1 should be 3.0.0

**Comment by Venti-** [comment]
Ok I see now, that makes sense. So what I should do, is to increment the major version now and do a new release?

Also, I think we should probably get rhid of the API versioning in the function name alltogether, now that we have the soname versioning working (kind of).

**Comment by marillat** [comment]
Yes, a new release with a major soname set to 3 is the best.

And yes the API versioning in the function name is a bad idea.

**Comment by Venti-** [comment]
Done. Also added a checklist to the version numbering to try and avoid this in the future.

Thanks for you help.
