### ISSUE TITLE
./configure: line 12368: syntax error near unexpected token `-mavx2,'

### ISSUE THREAD

**Issue by Selur** [ultravideo/kvazaar#125]
configure on OS X fails with:

> acMini:kvazaar selur$ ./configure 
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... build-aux/install-sh -c -d
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports nested variables... (cached) yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking for style of include used by make... GNU
checking dependency style of gcc... gcc3
checking for gcc option to accept ISO C99... none needed
checking for ar... ar
checking the archiver (ar) interface... ar
checking for special C compiler options needed for large files... no
checking for _FILE_OFFSET_BITS value needed for large files... no
checking build system type... x86_64-apple-darwin15.3.0
checking host system type... x86_64-apple-darwin15.3.0
checking how to print strings... printf
checking for a sed that does not truncate output... /usr/bin/sed
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for fgrep... /usr/bin/grep -F
checking for ld used by gcc... /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld
checking if the linker (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld) is GNU ld... no
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm
checking the name lister (/usr/bin/nm) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 196608
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... yes
checking how to convert x86_64-apple-darwin15.3.0 file names to x86_64-apple-darwin15.3.0 format... func_convert_file_noop
checking how to convert x86_64-apple-darwin15.3.0 file names to toolchain format... func_convert_file_noop
checking for /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld option to reload object files... -r
checking for objdump... no
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for archiver @FILE support... no
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm output from gcc object... ok
checking for sysroot... no
checking for mt... no
checking if : is a manifest tool... no
checking for dsymutil... dsymutil
checking for nmedit... nmedit
checking for lipo... lipo
checking for otool... otool
checking for otool64... no
checking for -single_module linker flag... yes
checking for -exported_symbols_list linker flag... yes
checking for -force_load linker flag... yes
checking how to run the C preprocessor... gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... yes
checking for gcc option to produce PIC... -fno-common -DPIC
checking if gcc PIC flag -fno-common -DPIC works... yes
checking if gcc static flag -static works... no
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld) supports shared libraries... yes
checking dynamic linker characteristics... darwin15.3.0 dyld
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
./configure: line 12368: syntax error near unexpected token `-mavx2,'
./configure: line 12368: `AX_CHECK_COMPILE_FLAG(-mavx2,   flag_avx2="true")'

**Comment by Venti-** [comment]
I'm not sure why that would affect only Mac, but I hope it helps.

**Comment by Venti-** [comment]
I added a TravisCI osx build, but was unable to replicate this issue. It's probably autotools version specific.

@Selur did this get fixed for you?

**Comment by Selur** [comment]
nope, but i'll try if updating autoconf helps. :)
Might take till the weekend to test properly

**Comment by Selur** [comment]
updating autoconf and a clean checkout helped with the configure call, but now the make call aborts:

> MacMini:kvazaar selur$ make
/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-recursive
Making all in src
  CC       bitstream.lo
  CC       cabac.lo
  CC       checkpoint.lo
  CC       cfg.lo
  CC       context.lo
  CC       cu.lo
  CC       encoder.lo
  CC       encoderstate.lo
  CC       encoder_state-bitstream.lo
  CC       encoder_state-ctors_dtors.lo
  CC       encoder_state-geometry.lo
  CC       filter.lo
  CC       image.lo
  CC       imagelist.lo
  CC       input_frame_buffer.lo
  CC       inter.lo
  CC       intra.lo
  CC       kvazaar.lo
  CC       nal.lo
  CC       rate_control.lo
  CC       rdo.lo
  CC       sao.lo
  CC       scalinglist.lo
  CC       search.lo
  CC       search_inter.lo
  CC       search_intra.lo
  CC       tables.lo
  CC       threadqueue.lo
  CC       transform.lo
  CC       videoframe.lo
  CC       strategies/generic/dct-generic.lo
  CC       strategies/generic/intra-generic.lo
  CC       strategies/generic/ipol-generic.lo
  CC       strategies/generic/nal-generic.lo
  CC       strategies/generic/picture-generic.lo
  CC       strategies/generic/quant-generic.lo
  CC       strategies/strategies-dct.lo
  CC       strategies/strategies-intra.lo
  CC       strategies/strategies-ipol.lo
  CC       strategies/strategies-nal.lo
  CC       strategies/strategies-picture.lo
  CC       strategies/strategies-quant.lo
  CC       strategies/x86_asm/picture-x86-asm.lo
  CC       strategyselector.lo
  CC       strategies/altivec/libaltivec_la-picture-altivec.lo
  CCLD     libaltivec.la
  CC       strategies/avx2/libavx2_la-dct-avx2.lo
  CC       strategies/avx2/libavx2_la-intra-avx2.lo
  CC       strategies/avx2/libavx2_la-ipol-avx2.lo
  CC       strategies/avx2/libavx2_la-picture-avx2.lo
  CC       strategies/avx2/libavx2_la-quant-avx2.lo
  CCLD     libavx2.la
  CC       strategies/sse2/libsse2_la-picture-sse2.lo
  CCLD     libsse2.la
  CC       strategies/sse41/libsse41_la-picture-sse41.lo
  CCLD     libsse41.la
  YASM     strategies/x86_asm/picture-x86-asm-sad.lo
  YASM     strategies/x86_asm/picture-x86-asm-satd.lo
  CCLD     libasm.la
  CCLD     libkvazaar.la
clang: warning: argument unused during compilation: '-pthread'
clang: warning: argument unused during compilation: '-pthread'
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: .libs/libkvazaar.a(checkpoint.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: .libs/libkvazaar.a(checkpoint.o) has no symbols
  CC       encmain.o
  CC       cli.o
  CC       yuv_io.o
  CCLD     kvazaar
clang: error: argument unused during compilation: '-pthread'
clang: error: argument unused during compilation: '-pthread'
make[2]: *** [kvazaar] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

**Comment by Venti-** [comment]
Some versions of Clang complain about -pthread being given to linker. Please use --disable-werror with configure to get around it.

**Comment by Selur** [comment]
that seems to do the job, thanks!
