### ISSUE TITLE
autoreconf not found

### ISSUE THREAD

**Issue by zuzudpom** [ultravideo/kvazaar#126]
Hello,
I don't understand why because on my computer (Linux Mint) I didn't find this problem one month ago but now I try to compile the kvazaar program on another computer (Ubuntu) to then execute the encoder and since the execution of the command ./autogen.sh, I got an error because it cannot find the autoreconf which is executed in autogen. I would like to know how to solve this problem please.
Best regards

**Comment by Venti-** [comment]
I recommend installing autoreconf.

**Comment by zuzudpom** [comment]
Where I can find it? Because with an apt-get install, it wasn't able to locate it.

**Comment by fador** [comment]
I believe the needed packages are:
automake
autoconf
libtool

**Comment by zuzudpom** [comment]
Thank you a lot, now it compiles :+1: . I just have a problem during the execution about the libkvazaar.so.3 but I think it comes from the file that I used to execute the encoder.

**Comment by Venti-** [comment]
If you build a shared library, src/kvazaar should be a libtool wrapper scripts that takes care or finding the so-file. If you call src/.libs/kvazaar directly or maybe if you make install into a weird prefix, you have to set LD_LIBRARY_PATH as instructed by libtool during make install.

If you don't want to deal with all of that and are fine with a static build, you can ./configure --disable-shared to compile just the static version.
