### ISSUE TITLE
Have NAL-unit type implemented yet?

### ISSUE THREAD

**Issue by ChuBro** [ultravideo/kvazaar#127]
I’ve created a socket program recently.  But it will use the NAL unit type to decide the state(which I set).  I’m wondering whether Kvazaar have the ability to separate all the kinds of NAL unit type.  If so, what is the option parameter I should add when I’m compressing?  
Cause it seems not to completely support the NAL unit type in common use. 

I was using this command:
kvazaar -i file.yuv --input-res 1280x720 -o file.hevc -n 500 -q 25

But the output bitstream is not quite match the definition of H.265 manual.
Or if I were wrong please tell me. THKS

**Comment by Venti-** [comment]
What is wrong with the bitstream?

I also don't understand what you mean by supporting NAL unit types. We use the ones we need, and to my best knowledge we do it according to standard.
