### ISSUE TITLE
.libs/libkvazaar.a(libkvazaar_la-checkpoint.o) has no symbols

### ISSUE THREAD

**Issue by Selur** [ultravideo/kvazaar#130]
trying to compile on mac:
> clang: warning: argument unused during compilation: '-pthread'
clang: warning: argument unused during compilation: '-pthread'
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: .libs/libkvazaar.a(libkvazaar_la-checkpoint.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: .libs/libkvazaar.a(libkvazaar_la-checkpoint.o) has no symbols
  CC       kvazaar-encmain.o
  CC       kvazaar-cli.o
  CC       kvazaar-yuv_io.o
  CCLD     kvazaar
clang: error: argument unused during compilation: '-pthread'
clang: error: argument unused during compilation: '-pthread'

**Comment by fador** [comment]
Hi!

Could you try using
./configure --disable-werror

That's what we do in travis build with osx =)

**Comment by Venti-** [comment]
I think this has been solved by  4eaacbe.
