### ISSUE TITLE
syntax error near unexpected token `cryptopp,'

### ISSUE THREAD

**Issue by Selur** [ultravideo/kvazaar#138]
this is what I get when I call configure:
./configure: line 16150: syntax error near unexpected token `cryptopp,'
./configure: line 16150:`    PKG_CHECK_MODULES(cryptopp, cryptopp,'

**Comment by Venti-** [comment]
Works for me, but it looks like some arguments are not quoted around that line. Hopefully quoting them will fix the issue. Some examples show use of unquoted arguments, so I'm not sure when it's ok to leave the quotes out.

**Comment by Venti-** [comment]
@Selur did the fix resolve your issue?

**Comment by Selur** [comment]
No clue, now it stops at the autopen-step,...
I did a clean git clone `git clone https://github.com/ultravideo/kvazaar.git`
and then:
> macmini:workspace selur$ cd kvazaar/
macmini:kvazaar selur$ ls
COPYING		CREDITS		Dockerfile	Makefile.am	README.md	autogen.sh	bin		build		configure.ac	doc		docs.doxy	greatest	m4		src		tests		tools
macmini:kvazaar selur$ ./autogen.sh 
Submodule 'greatest' (https://github.com/ultravideo/greatest.git) registered for path 'greatest'
Cloning into 'greatest'...
remote: Counting objects: 354, done.
remote: Total 354 (delta 0), reused 0 (delta 0), pack-reused 354
Receiving objects: 100% (354/354), 128.31 KiB | 0 bytes/s, done.
Resolving deltas: 100% (206/206), done.
Checking connectivity... done.
Submodule path 'greatest': checked out '60e25ce7658ced49f03b52ac14c553cf6ea33de4'
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, `build-aux'.
libtoolize: copying file `build-aux/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIR, `m4'.
libtoolize: copying file `m4/libtool.m4'
libtoolize: copying file `m4/ltoptions.m4'
libtoolize: copying file `m4/ltsugar.m4'
libtoolize: copying file `m4/ltversion.m4'
libtoolize: copying file `m4/lt~obsolete.m4'
configure.ac:64: error: possibly undefined macro: AC_DEFINE
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:65: error: possibly undefined macro: AC_MSG_ERROR
autoreconf: /usr/local/autoconf-2.69/bin/autoconf failed with exit status: 1

**Comment by fador** [comment]
I noticed that the same problem was fixed on Ubuntu when I installed pkgconf

**Comment by Arizer** [comment]
Anything new on this?

**Comment by Venti-** [comment]
I think this is indeed about missing pkg-config. We should check that it exist and give error on that instead of AC_DEFINE.
