### ISSUE TITLE
Visual Studio 2015 build issues

### ISSUE THREAD

**Issue by tnti** [ultravideo/kvazaar#139]
Error message

1> ------ Rebuild All started: Project: kvazaar_lib, Configuration: Release x64 ------
1> Assembling x86inc.asm
1> Assembling picture-x86-asm-sad.asm
1> Assembling picture-x86-asm-satd.asm
1> crypto.cpp
1> libmd5.c
1> input_frame_buffer.c
1> D: \ Program Files (x86) \ Microsoft Visual Studio 14.0 \ VC \ include \ pthread.h (320): error C2011: "timespec": "struct" type redefinition
1> C: \ Program Files (x86) \ Windows Kits \ 10 \ Include \ 10.0.10240.0 \ ucrt \ time.h (39): note: See "timespec" statement
1> kvazaar.c
1> D: \ Program Files (x86) \ Microsoft Visual Studio 14.0 \ VC \ include \ pthread.h (320): error C2011: "timespec": "struct" type redefinition
1> C: \ Program Files (x86) \ Windows Kits \ 10 \ Include \ 10.0.10240.0 \ ucrt \ time.h (39): note: See "timespec" statement
1> bitstream.c
1> cabac.c
1> D: \ Program Files (x86) \ Microsoft Visual Studio 14.0 \ VC \ include \ pthread.h (320): error C2011: "timespec": "struct" type redefinition
1> C: \ Program Files (x86) \ Windows Kits \ 10 \ Include \ 10.0.10240.0 \ ucrt \ time.h (39): note: See "timespec" statement
1> cfg.c
1> context.c
1> D: \ Program Files (x86) \ Microsoft Visual Studio 14.0 \ VC \ include \ pthread.h (320): error C2011: "timespec": "struct" type redefinition
1> C: \ Program Files (x86) \ Windows Kits \ 10 \ Include \ 10.0.10240.0 \ ucrt \ time.h (39): note: See "timespec" statement
1> cu.c
1> D: \ Program Files (x86) \ Microsoft Visual Studio 14.0 \ VC \ include \ pthread.h (320): error C2011: "timespec": "struct" type redefinition
1> C: \ Program Files (x86) \ Windows Kits \ 10 \ Include \ 10.0.10240.0 \ ucrt \ time.h (39): note: See "timespec" statement
1> encoder.c
1> D: \ Program Files (x86) \ Microsoft Visual Studio 14.0 \ VC \ include \ pthread.h (320): error C2011: "timespec": "struct" type redefinition
1> C: \ Program Files (x86) \ Windows Kits \ 10 \ Include \ 10.0.10240.0 \ ucrt \ time.h (39): note: See "timespec" statement
1> encoderstate.c
1> D: \ Program Files (x86) \ Microsoft Visual Studio 14.0 \ VC \ include \ pthread.h (320): error C2011: "timespec": "struct" type redefinition
1> C: \ Program Files (x86) \ Windows Kits \ 10 \ Include \ 10.0.10240.0 \ ucrt \ time.h (39): note: See "timespec" statement
1> encoder_state-bitstream.c
1> D: \ Program Files (x86) \ Microsoft Visual Studio 14.0 \ VC \ include \ pthread.h (320): error C2011: "timespec": "struct" type redefinition
1> C: \ Program Files (x86) \ Windows Kits \ 10 \ Include \ 10.0.10240.0 \ ucrt \ time.h (39): note: See "timespec" statement
1> encoder_state-ctors_dtors.c
1> D: \ Program Files (x86) \ Microsoft Visual Studio 14.0 \ VC \ include \ pthread.h (320): error C2011: "timespec": "struct" type redefinition
1> C: \ Program Files (x86) \ Windows Kits \ 10 \ Include \ 10.0.10240.0 \ ucrt \ time.h (39): note: See "timespec" statement
1> encoder_state-geometry.c
1> D: \ Program Files (x86) \ Microsoft Visual Studio 14.0 \ VC \ include \ pthread.h (320): error C2011: "timespec": "struct" type redefinition
1> C: \ Program Files (x86) \ Windows Kits \ 10 \ Include \ 10.0.10240.0 \ ucrt \ time.h (39): note: See "timespec" statement
1> encode_coding_tree.c
1> D: \ Program Files (x86) \ Microsoft Visual Studio 14.0 \ VC \ include \ pthread.h (320): error C2011: "timespec": "struct" type redefinition
1> C: \ Program Files (x86) \ Windows Kits \ 10 \ Include \ 10.0.10240.0 \ ucrt \ time.h (39): note: See "timespec" statement
1> getopt.c
1> filter.c
1> D: \ Program Files (x86) \ Microsoft Visual Studio 14.0 \ VC \ include \ pthread.h (320): error C2011: "timespec": "struct" type redefinition
1> C: \ Program Files (x86) \ Windows Kits \ 10 \ Include \ 10.0.10240.0 \ ucrt \ time.h (39): note: See "timespec" statement
1> image.c
1> D: \ Program Files (x86) \ Microsoft Visual Studio 14.0 \ VC \ include \ pthread.h (320): error C2011: "timespec": "struct" type redefinition
1> C: \ Program Files (x86) \ Windows Kits \ 10 \ Include \ 10.0.10240.0 \ ucrt \ time.h (39): note: See "timespec" statement
1> imagelist.c
1> D: \ Program Files (x86) \ Microsoft Visual Studio 14.0 \ VC \ include \ pthread.h (320): error C2011: "timespec": "struct" type redefinition
1> C: \ Program Files (x86) \ Windows Kits \ 10 \ Include \ 10.0.10240.0 \ ucrt \ time.h (39): note: See "timespec" statement
1> inter.c
1> D: \ Program Files (x86) \ Microsoft Visual Studio 14.0 \ VC \ include \ pthread.h (320): error C2011: "timespec": "struct" type redefinition
1> C: \ Program Files (x86) \ Windows Kits \ 10 \ Include \ 10.0.10240.0 \ ucrt \ time.h (39): note: See "timespec" statement
1> Compiling ...
1> intra.c
1> D: \ Program Files (x86) \ Microsoft Visual Studio 14.0 \ VC \ include \ pthread.h (320): error C2011: "timespec": "struct" type redefinition
1> C: \ Program Files (x86) \ Windows Kits \ 10 \ Include \ 10.0.10240.0 \ ucrt \ time.h (39): note: See "timespec" statement
1> nal.c
1> rate_control.c
1> D: \ Program Files (x86) \ Microsoft Visual Studio 14.0 \ VC \ include \ pthread.h (320): error C2011: "timespec": "struct" type redefinition
1> C: \ Program Files (x86) \ Windows Kits \ 10 \ Include \ 10.0.10240.0 \ ucrt \ time.h (39): note: See "timespec" statement
1> rdo.c
1> D: \ Program Files (x86) \ Microsoft Visual Studio 14.0 \ VC \ include \ pthread.h (320): error C2011: "timespec": "struct" type redefinition
1> C: \ Program Files (x86) \ Windows Kits \ 10 \ Include \ 10.0.10240.0 \ ucrt \ time.h (39): note: See "timespec" statement
1> sao.c
1> D: \ Program Files (x86) \ Microsoft Visual Studio 14.0 \ VC \ include \ pthread.h (320): error C2011: "timespec": "struct" type redefinition
1> C: \ Program Files (x86) \ Windows Kits \ 10 \ Include \ 10.0.10240.0 \ ucrt \ time.h (39): note: See "timespec" statement
1> scalinglist.c
1> search.c
1> D: \ Program Files (x86) \ Microsoft Visual Studio 14.0 \ VC \ include \ pthread.h (320): error C2011: "timespec": "struct" type redefinition
1> C: \ Program Files (x86) \ Windows Kits \ 10 \ Include \ 10.0.10240.0 \ ucrt \ time.h (39): note: See "timespec" statement
1> search_inter.c
1> D: \ Program Files (x86) \ Microsoft Visual Studio 14.0 \ VC \ include \ pthread.h (320): error C2011: "timespec": "struct" type redefinition
1> C: \ Program Files (x86) \ Windows Kits \ 10 \ Include \ 10.0.10240.0 \ ucrt \ time.h (39): note: See "timespec" statement
1> .. \ .. \ src \ search_inter.c (1704): warning C4457: "y" to hide the function parameter declarations
Statement See "y" is: 1> .. \ .. \ src \ search_inter.c (1670): note
1> .. \ .. \ src \ search_inter.c (1705): warning C4457: "x" to hide the function parameter declarations
1> .. \ .. \ src \ search_inter.c (1670): note: See the "x" statement
1> search_intra.c
1> D: \ Program Files (x86) \ Microsoft Visual Studio 14.0 \ VC \ include \ pthread.h (320): error C2011: "timespec": "struct" type redefinition
1> C: \ Program Files (x86) \ Windows Kits \ 10 \ Include \ 10.0.10240.0 \ ucrt \ time.h (39): note: See "timespec" statement
1> intra-generic.c
1> D: \ Program Files (x86) \ Microsoft Visual Studio 14.0 \ VC \ include \ pthread.h (320): error C2011: "timespec": "struct" type redefinition
1> C: \ Program Files (x86) \ Windows Kits \ 10 \ Include \ 10.0.10240.0 \ ucrt \ time.h (39): note: See "timespec" statement
1> quant-generic.c
1> D: \ Program Files (x86) \ Microsoft Visual Studio 14.0 \ VC \ include \ pthread.h (320): error C2011: "timespec": "struct" type redefinition
1> C: \ Program Files (x86) \ Windows Kits \ 10 \ Include \ 10.0.10240.0 \ ucrt \ time.h (39): note: See "timespec" statement
1> sao-generic.c
1> D: \ Program Files (x86) \ Microsoft Visual Studio 14.0 \ VC \ include \ pthread.h (320): error C2011: "timespec": "struct" type redefinition
1> C: \ Program Files (x86) \ Windows Kits \ 10 \ Include \ 10.0.10240.0 \ ucrt \ time.h (39): note: See "timespec" statement
1> strategies-intra.c
1> D: \ Program Files (x86) \ Microsoft Visual Studio 14.0 \ VC \ include \ pthread.h (320): error C2011: "timespec": "struct" type redefinition
1> C: \ Program Files (x86) \ Windows Kits \ 10 \ Include \ 10.0.10240.0 \ ucrt \ time.h (39): note: See "timespec" statement
1> strategies-quant.c
1> D: \ Program Files (x86) \ Microsoft Visual Studio 14.0 \ VC \ include \ pthread.h (320): error C2011: "timespec": "struct" type redefinition
1> C: \ Program Files (x86) \ Windows Kits \ 10 \ Include \ 10.0.10240.0 \ ucrt \ time.h (39): note: See "timespec" statement
1> picture-altivec.c
1> dct-generic.c
1> D: \ Program Files (x86) \ Microsoft Visual Studio 14.0 \ VC \ include \ pthread.h (320): error C2011: "timespec": "struct" type redefinition
1> C: \ Program Files (x86) \ Windows Kits \ 10 \ Include \ 10.0.10240.0 \ ucrt \ time.h (39): note: See "timespec" statement
1> ipol-generic.c
1> D: \ Program Files (x86) \ Microsoft Visual Studio 14.0 \ VC \ include \ pthread.h (320): error C2011: "timespec": "struct" type redefinition
1> C: \ Program Files (x86) \ Windows Kits \ 10 \ Include \ 10.0.10240.0 \ ucrt \ time.h (39): note: See "timespec" statement
1> nal-generic.c
1> D: \ Program Files (x86) \ Microsoft Visual Studio 14.0 \ VC \ include \ pthread.h (320): error C2011: "timespec": "struct" type redefinition
1> C: \ Program Files (x86) \ Windows Kits \ 10 \ Include \ 10.0.10240.0 \ ucrt \ time.h (39): note: See "timespec" statement
1> picture-generic.c
1> D: \ Program Files (x86) \ Microsoft Visual Studio 14.0 \ VC \ include \ pthread.h (320): error C2011: "timespec": "struct" type redefinition
1> C: \ Program Files (x86) \ Windows Kits \ 10 \ Include \ 10.0.10240.0 \ ucrt \ time.h (39): note: See "timespec" statement
1> picture-sse2.c
1> D: \ Program Files (x86) \ Microsoft Visual Studio 14.0 \ VC \ include \ pthread.h (320): error C2011: "timespec": "struct" type redefinition
1> C: \ Program Files (x86) \ Windows Kits \ 10 \ Include \ 10.0.10240.0 \ ucrt \ time.h (39): note: See "timespec" statement
1> Compiling ...
1> picture-sse41.c
1> D: \ Program Files (x86) \ Microsoft Visual Studio 14.0 \ VC \ include \ pthread.h (320): error C2011: "timespec": "struct" type redefinition
1> C: \ Program Files (x86) \ Windows Kits \ 10 \ Include \ 10.0.10240.0 \ ucrt \ time.h (39): note: See "timespec" statement
1> strategies-dct.c
1> D: \ Program Files (x86) \ Microsoft Visual Studio 14.0 \ VC \ include \ pthread.h (320): error C2011: "timespec": "struct" type redefinition
1> C: \ Program Files (x86) \ Windows Kits \ 10 \ Include \ 10.0.10240.0 \ ucrt \ time.h (39): note: See "timespec" statement
1> strategies-ipol.c
1> D: \ Program Files (x86) \ Microsoft Visual Studio 14.0 \ VC \ include \ pthread.h (320): error C2011: "timespec": "struct" type redefinition
1> C: \ Program Files (x86) \ Windows Kits \ 10 \ Include \ 10.0.10240.0 \ ucrt \ time.h (39): note: See "timespec" statement
1> strategies-nal.c
1> strategies-picture.c
1> D: \ Program Files (x86) \ Microsoft Visual Studio 14.0 \ VC \ include \ pthread.h (320): error C2011: "timespec": "struct" type redefinition
1> C: \ Program Files (x86) \ Windows Kits \ 10 \ Include \ 10.0.10240.0 \ ucrt \ time.h (39): note: See "timespec" statement
1> strategies-sao.c
1> D: \ Program Files (x86) \ Microsoft Visual Studio 14.0 \ VC \ include \ pthread.h (320): error C2011: "timespec": "struct" type redefinition
1> C: \ Program Files (x86) \ Windows Kits \ 10 \ Include \ 10.0.10240.0 \ ucrt \ time.h (39): note: See "timespec" statement
1> picture-x86-asm.c
1> D: \ Program Files (x86) \ Microsoft Visual Studio 14.0 \ VC \ include \ pthread.h (320): error C2011: "timespec": "struct" type redefinition
1> C: \ Program Files (x86) \ Windows Kits \ 10 \ Include \ 10.0.10240.0 \ ucrt \ time.h (39): note: See "timespec" statement
1> videoframe.c
1> D: \ Program Files (x86) \ Microsoft Visual Studio 14.0 \ VC \ include \ pthread.h (320): error C2011: "timespec": "struct" type redefinition
1> C: \ Program Files (x86) \ Windows Kits \ 10 \ Include \ 10.0.10240.0 \ ucrt \ time.h (39): note: See "timespec" statement
1> strategyselector.c
1> D: \ Program Files (x86) \ Microsoft Visual Studio 14.0 \ VC \ include \ pthread.h (320): error C2011: "timespec": "struct" type redefinition
1> C: \ Program Files (x86) \ Windows Kits \ 10 \ Include \ 10.0.10240.0 \ ucrt \ time.h (39): note: See "timespec" statement
1> tables.c
1> threadqueue.c
1> D: \ Program Files (x86) \ Microsoft Visual Studio 14.0 \ VC \ include \ pthread.h (320): error C2011: "timespec": "struct" type redefinition
1> C: \ Program Files (x86) \ Windows Kits \ 10 \ Include \ 10.0.10240.0 \ ucrt \ time.h (39): note: See "timespec" statement
1> transform.c
1> D: \ Program Files (x86) \ Microsoft Visual Studio 14.0 \ VC \ include \ pthread.h (320): error C2011: "timespec": "struct" type redefinition
1> C: \ Program Files (x86) \ Windows Kits \ 10 \ Include \ 10.0.10240.0 \ ucrt \ time.h (39): note: See "timespec" statement
2> ------ skipped Rebuild All: Project: kvazaar_tests, Configuration: Release x64 ------
2> No solution configuration selected for this project to be generated
3> ------ Rebuild All started: Project: kvazaar_cli, Configuration: Release x64 ------
3> cli.c
3> encmain.c
3> D: \ Program Files (x86) \ Microsoft Visual Studio 14.0 \ VC \ include \ pthread.h (320): error C2011: "timespec": "struct" type redefinition
3> C: \ Program Files (x86) \ Windows Kits \ 10 \ Include \ 10.0.10240.0 \ ucrt \ time.h (39): note: See "timespec" statement
3> yuv_io.c
========== Rebuild All: Success 0, failed two, skip a ==========

The reason is defined in pthread.h in timespec and c ++ standard header file time.h defined in timespec repeat

How to solve？

My English isn't very good, please don't mind.

**Comment by tnti** [comment]
Add #define _CRT_NO_TIME_T 1

You may be able to solve the problem

But I do not know where to add

**Comment by Venti-** [comment]
You need to put HAVE_STRUCT_TIMESPEC in preprocessor definitions.

**Comment by tnti** [comment]
After modifying

Error Message

1> ------ Rebuild All started: Project: kvazaar_lib, Configuration: Debug Win32 ------
1> Assembling x86inc.asm
1> Assembling picture-x86-asm-sad.asm
1> Assembling picture-x86-asm-satd.asm
1> C: \ Program Files (x86) \ MSBuild \ Microsoft.Cpp \ v4.0 \ V140 \ BuildCustomizations \ vsyasm.targets (45,5): error MSB3721: Command "" D: \ Program Files (x86) \ Microsoft Visual Studio 14.0 \ VC \ bin \ "vsyasm.exe -Xvc -f Win32 -i" Z: \ kvazaar-master \ kvazaar-master \ build \ .. \ src \ extras "-d" ARCH_X86_64 = 0 "-d" PREFIX "-o" Win32-Debug \\ "-rnasm -pnasm" .. \ .. \ src \ strategies \ x86_asm \ picture-x86-asm-sad.asm "" .. \ .. \ src \ strategies \ x86_asm \ picture-x86-asm-satd.asm "" exited with return code 1.
2> ------ skipped Rebuild All: Project: kvazaar_tests, Configuration: Debug Win32 ------
2> No solution configuration selected for this project to be generated
3> ------ Rebuild All started: Project: kvazaar_cli, Configuration: Debug Win32 ------
3> yuv_io.c
3> encmain.c
3> cli.c
3> Generating Code ...
3> LINK: fatal error LNK1104: can not open file "Z: \ kvazaar-master \ kvazaar-master \ build \ Win32-Debug-libs \ kvazaar_lib.lib"
========== Rebuild All: Success 0, failed two, skip a ==========

**Comment by Venti-** [comment]
Hmm, I don't know. Maybe you are hitting this bug https://tortall.lighthouseapp.com/projects/78676/tickets/276-format-win32-fails-default-platform-name-in-vs in vsyasm 1.3.0? If so, you need to use 1.2.0 or a development version.

**Comment by tnti** [comment]
It has been resolved

thank you very much

Need
threads.h threadsqueue.h threadueue.c encmain.c
Add to
#define HAVE_STRUCT_TIMESPEC
#include <pthread.h>

Copy pthreadVC2.lib to kvazaar_lib


Copy pthreadVC2.dll to kvazaar.exe

Use vsyasm 1.3.0 no errors
