### ISSUE TITLE
Please release dist-tarballs

### ISSUE THREAD

**Issue by darealshinji** [ultravideo/kvazaar#146]
Can you please add tarballs to the release section that were created with `git checkout ${version} && ./autogen.sh && ./configure && make dist` for future releases? The tarballs generated by Github are a bit useless because I can't checkout the git submodules there.

**Comment by Venti-** [comment]
Ok, we will. We should make a checklist/script on stuff that needs doing to make a release, so I will leave this open until I add that list.

**Comment by Venti-** [comment]
We will include tarballs as directed from now on.
