### ISSUE TITLE
Kvazaar doesn't build on Ubuntu due to many errors in Header files.

### ISSUE THREAD

**Issue by omar-ECE** [ultravideo/kvazaar#149]
when trying to build Kvazaar code following the mentioned steps in the Readme file: ./autogen.sh ./configure make, but i faced a lot of errors in Header files particularly **_"sched.h"_** and **_"pthread.h"_**.

**Comment by Venti-** [comment]
What kind of errors? At least CI tests on Ubuntu 12.04 compile without warnings: https://travis-ci.org/ultravideo/kvazaar/jobs/176765977

Also, these are system headers, and not part of Kvazaar. Is some prerequisite is missing from the readme?
