### ISSUE TITLE
Don't find constant rate factor (crf) parameter, just "qp".

### ISSUE THREAD

**Issue by fjodorov55** [ultravideo/kvazaar#150]
Hi

I want to try this encoder, but don't find the crf parameter setting, just the qp. It's not supported?

Where is the documentation for this? 

Thanks

**Comment by fador** [comment]
Hi,

crf is not supported at the moment so qp is the only way to define "constant quality".

We will look at adding crf at some point, but for now we don't have that in the roadmap

**Comment by fjodorov55** [comment]
Thank you :) 
No problem, I just waiting for it.
Have a nice day
