### ISSUE TITLE
binarizer

### ISSUE THREAD

**Issue by codernemesis** [ultravideo/kvazaar#152]
Hi Ari,
  I want to ask about CABAC Binarizer module that convert syntax element to bins. In kvazaar, which file/function is doing the binarization.
Thanks.

**Comment by Venti-** [comment]
There are some generic binarization routines in cabac.c, like Exp-Golomb, but most of the binarization is done during bitstream generation. For example in [encode_coding_tree.c:812](https://github.com/ultravideo/kvazaar/blob/master/src/encode_coding_tree.c#L812). Does that answer your question?

**Comment by codernemesis** [comment]
I want to do just binarizer side of CABAC.  How can I do with kvazar and which way is suitable to test it. Could you give me your mail address.

**Comment by Venti-** [comment]
If you want to help improve Kvazaar by modularizing the binarization, or whatever you want to do, that would probably be welcome. My email is ari@koivu.la.
