### ISSUE TITLE
HM binarization

### ISSUE THREAD

**Issue by codernemesis** [ultravideo/kvazaar#167]
Hi All,
    I want to  compile kvazaar in windows and I want to write of the "binarization" outputs to a file .
How can I do that(compile on windows and writing outputs to a file )
Thanks in advance for your help.
Greetings.

**Comment by aryla** [comment]
For compiling on Windows, follow the instructions in the [readme](https://github.com/ultravideo/kvazaar#compiling-kvazaar) and then build `build/kvazaar_VS2013.sln` in Visual Studio.

Unfortunately, kvazaar doesn't have an option for outputting the binarization results. You would need to patch `cabac.c` and `encode_coding_tree.c`. Good luck!
