### ISSUE TITLE
Problems compiling kvazaar

### ISSUE THREAD

**Issue by paulhiggs** [ultravideo/kvazaar#168]
Hi, I am having trouble compiling kvazaar using Microsoft Visual Studio Community 2017, Version 15.1 (26403.0) Release and yasm 1.3.0.

When building kvazaar_lib I get the following error and warning.

```
Error	MSB3721	The command "vsyasm.exe -Xvc -f x64 -i "D:\code\kvazaar-master\build\..\src\extras" -d "ARCH_X86_64=1" -d "HAVE_ALIGNED_STACK=1" -o "x64-Debug\\" -rnasm -pnasm   "..\..\src\strategies\x86_asm\picture-x86-asm-sad.asm"  "..\..\src\strategies\x86_asm\picture-x86-asm-satd.asm"" exited with code 1.	kvazaar_lib	D:\code\kvazaar-master\build\yasm\vsyasm.targets	45
Warning		can open only one input file, only the last file will be processed	kvazaar_lib	D:\code\kvazaar-master\build\kvazaar_lib\yasm	1		
```

global.h has `#define KVZ_VERSION 1.1.0`
	
I guess VS wants to compile both "picture-x86-asm-sad.asm" and "picture-x86-asm-satd.asm" with one command, but this is not allowed by YASM.
Any suggestions?

**Comment by paulhiggs** [comment]
Solved for x64 but Win32 build fails as `-f Win32` is not a valid option to yasm (but `-f win32` is)

**Comment by Arizer** [comment]
Hi,

there is already a fix for this in yasm, but sadly it is not included in 1.3.0
(https://tortall.lighthouseapp.com/projects/78676/tickets/276-format-win32-fails-default-platform-name-in-vs)

Using newer or older version (for example 1.2.0) of yasm should work.

**Comment by aryla** [comment]
I'll add a workaround for this in Kvazaar.

**Comment by aryla** [comment]
@paulhiggs, thanks for reporting this! By the way, how did you solve the original problem of two input files to YASM?

**Comment by paulhiggs** [comment]
For the multiple files, I re-extracted all the yasm files from the 1.3.0 zip. Perhaps therr was something different with the config file from.Vidual Studio or kvazaar (sorry, I have very limited yasm knowledge)

**Comment by aryla** [comment]
Okay, thanks,
