### ISSUE TITLE
Quality of each tile 

### ISSUE THREAD

**Issue by OmarEltobgy** [ultravideo/kvazaar#169]
Greetings, 

1. I would like to ask how to get a quality metric for each tile separately i.e. calculate psnr or ssim values for each tile. 

2. Also, I would like to know how to get the overall psnr or ssim ? There are 3 psnr values next to each line and at the end there are 3 average psnr values, I would like to know what each value represents ? 

Best Regards

**Comment by aryla** [comment]
1. You could decode the bitstream, crop it to the tile and then compare with the original video.

2. The first value is luma PSNR and the following two are chroma PSNR. I suppose we should make this more clear in the output. You'll probably want to use a weighted average of these.

**Comment by OmarEltobgy** [comment]
Thanks aryla for your helpful reply. 

However, Do you recommend any open source code to do this decoding ? 

Best Regards,
Omar

**Comment by aryla** [comment]
At least FFmpeg should be able to do that.

**Comment by aryla** [comment]
I changed the output format in e90bde5c62c20e6c6978ba5ced760db7da7e8447. The meaning of the PSNR values should be clear now.
