### ISSUE TITLE
powerpc/e500mc: altivec not supported on this target

### ISSUE THREAD

**Issue by RomainNaour** [ultravideo/kvazaar#174]
Hi,

On powerpc/e500mc altivec is not supported:

strategies/altivec/picture-altivec.c:1:0: error: AltiVec not supported in this target

http://autobuild.buildroot.net/results/76c/76c76191f84748326d76fe0cc89456a72738a06b/build-end.log

Best regards,
Romain

**Comment by aryla** [comment]
Thanks for the reports! Unfortunately, we are not experts in PowerPC/Altivec so it might take a while to get these fixed.
