### ISSUE TITLE
library loading error 

### ISSUE THREAD

**Issue by 21praveen** [ultravideo/kvazaar#175]
I am getting following error on ubuntu :
 kvazaar: error while loading shared libraries: libkvazaar.so.3: cannot open shared object file: No such file or directory. 

But the file is present at /usr/local/lib

**Comment by aryla** [comment]
You might need to run `sudo ldconfig` to add the library to the cache.

**Comment by 21praveen** [comment]
Thank You :)     That worked.

**Comment by aryla** [comment]
No problem!
