### ISSUE TITLE
no mode type chosen causing assert!

### ISSUE THREAD

**Issue by stuuu68** [ultravideo/kvazaar#176]
Under some conditions (usually high QP) I am seeing no mode chosen which causes an assert at the end of search_cu().

  ```
PERFORMANCE_MEASURE_END(KVZ_PERF_SEARCHCU, state->encoder_control->threadqueue, "type=search_cu,frame=%d,tile=%d,slice=%d,px_x=%d-%d,px_y=%d-%d,depth=%d,split=%d,cur_cu_is_intra=%d", state->frame->num, state->tile->id, state->slice->id,
                          (state->tile->lcu_offset_x * LCU_WIDTH) + x,
                          (state->tile->lcu_offset_x * LCU_WIDTH) + x + (LCU_WIDTH >> depth), 
                          (state->tile->lcu_offset_y * LCU_WIDTH) + y,
                          (state->tile->lcu_offset_y * LCU_WIDTH) + y + (LCU_WIDTH >> depth), 
                          depth, debug_split, (cur_cu->type==CU_INTRA)?1:0);

  assert(cur_cu->type != CU_NOTSET);     // <<<<<<<<<<<<<<<<<--here

  return cost;
}
```

This assert is clearly to catch a circumstance that shouldn't occur, so somewhere the costing are not forcing a decision. 

There's a check around line 633 which seems to try and catch this but it doesn't account for the condition where cu_dl is not set.
```
    // If no search is not performed for this depth, try just the best mode
    // of the top left CU from the next depth. This should ensure that 64x64
    // gets used, at least in the most obvious cases, while avoiding any
    // searching.
    if (cur_cu->type == CU_NOTSET && depth < MAX_PU_DEPTH
        && x + cu_width <= frame->width && y + cu_width <= frame->height)
```

**Comment by aryla** [comment]
Thanks for the bug report! Could you post the full command line used to run kvazaar and the output of `kvazaar --version`?

The check on line 663 is actually not intended for this case. The CU type should have been set after inter/intra search or in `work_tree_copy_up`.

**Comment by stuuu68** [comment]
OK. I am currently only seeing this in my ported copy which is running on an embedded device so I can't reproduce this use case exactly with the cmd line version. The logic hasn't changed in the ported code but I expect I am munging some data somewhere. If I can reproduce with cli I will let you know.

**Comment by stuuu68** [comment]
I have traced this problem to being caused by a misbehaving pow() function which messes up the calculation of lambda and so disrupts the mode choice by costing.
