### ISSUE TITLE
How to get a h265 file with the level Main@L5.1.

### ISSUE THREAD

**Issue by DanielChedj** [ultravideo/kvazaar#178]
Hello everybody,

I would like to decode a yuv file in h265 file. I would like to get at the end a file with a level Main@L5.1.
For the moment I use the standart command: * docker run -i -a STDIN -a STDOUT ultravideo / kvazaar -i - --input-res = 3840x1920 -o - <input.yuv> out <output.h265> *. But at the end I always have a file with the level Main@L6.2. 
- What is the command I need to write, to get a file with a level Main@L5.1 ?
- Which parameters ar important if i want to set te level (Main@L5.1, 5.2, 6.2 ............)of a file.

Thank you for your help.

**Comment by Arizer** [comment]
Hi and sorry for the long wait,

Kvazaar supports only L6.2 and there are no options to change it currently. I'm not sure when options for the other levels will be added. Adding them should be fairly simple, but we have not really needed this feature so far. Requirements for the tiers and levels can be found here: https://en.wikipedia.org/wiki/High_Efficiency_Video_Coding_tiers_and_levels

**Comment by fador** [comment]
Support for changing the level was added in bac07457
Try using `--level=5.1`
