### ISSUE TITLE
LNK1181	cannot open input file 'x64-Release\picture-x86-asm-sad.obj'

### ISSUE THREAD

**Issue by kuh3h3** [ultravideo/kvazaar#179]
tried to build on windows 10 with visual studio 2017 preview 3.
but failed. maybe  something wrong in solution upgrade process.

1>------ Build started: Project: kvazaar_lib, Configuration: Release x64 ------
1>crypto.cpp
1>libmd5.c
1>input_frame_buffer.c
1>kvazaar.c
1>bitstream.c
1>cabac.c
1>cfg.c
1>context.c
1>cu.c
1>encoder.c
1>encoderstate.c
1>encoder_state-bitstream.c
1>encoder_state-ctors_dtors.c
1>encoder_state-geometry.c
1>encode_coding_tree.c
1>..\..\src\encode_coding_tree.c(694): warning C4245: 'initializing': conversion from 'int' to 'const uint8_t', signed/unsigned mismatch
1>..\..\src\encode_coding_tree.c(695): warning C4245: 'initializing': conversion from 'int' to 'const uint8_t', signed/unsigned mismatch
1>..\..\src\encode_coding_tree.c(749): warning C4245: 'initializing': conversion from 'int' to 'uint8_t', signed/unsigned mismatch
1>getopt.c
1>filter.c
1>image.c
1>imagelist.c
1>inter.c
1>Compiling...
1>intra.c
1>nal.c
1>rate_control.c
1>rdo.c
1>sao.c
1>scalinglist.c
1>search.c
1>search_inter.c
1>..\..\src\search_inter.c(1554): warning C4457: declaration of 'y' hides function parameter
1>..\..\src\search_inter.c(1513): note: see declaration of 'y'
1>..\..\src\search_inter.c(1555): warning C4457: declaration of 'x' hides function parameter
1>..\..\src\search_inter.c(1513): note: see declaration of 'x'
1>search_intra.c
1>intra-generic.c
1>quant-generic.c
1>sao-generic.c
1>strategies-intra.c
1>strategies-quant.c
1>picture-altivec.c
1>dct-generic.c
1>ipol-generic.c
1>nal-generic.c
1>picture-generic.c
1>picture-sse2.c
1>Compiling...
1>picture-sse41.c
1>strategies-dct.c
1>strategies-ipol.c
1>strategies-nal.c
1>strategies-picture.c
1>strategies-sao.c
1>picture-x86-asm.c
1>videoframe.c
1>strategyselector.c
1>tables.c
1>threadqueue.c
1>transform.c
1>intra-avx2.c
1>quant-avx2.c
1>sao-avx2.c
1>dct-avx2.c
1>ipol-avx2.c
1>..\..\src\strategies\avx2\ipol-avx2.c(1284): warning C4457: declaration of 'dst' hides function parameter
1>..\..\src\strategies\avx2\ipol-avx2.c(1239): note: see declaration of 'dst'
1>..\..\src\strategies\avx2\ipol-avx2.c(1348): warning C4457: declaration of 'dst' hides function parameter
1>..\..\src\strategies\avx2\ipol-avx2.c(1301): note: see declaration of 'dst'
1>picture-avx2.c
1>LINK : fatal error LNK1181: cannot open input file 'x64-Release\picture-x86-asm-sad.obj'
1>Done building project "kvazaar_lib.vcxproj" -- FAILED.

**Comment by kuh3h3** [comment]
I manually made that two objs.

vsyasm.exe -Xvc -f win64 -i "C:\Users\kuh3h\Downloads\kvazaar\build\..\src\extras" -d "ARCH_X86_64=1" -d "HAVE_ALIGNED_STACK=1" -o "x64-Release\\" -rnasm -pnasm   C:\Users\kuh3h\Downloads\kvazaar\src\strategies\x86_asm\picture-x86-asm-sad.asm

C:\Users\kuh3h\Downloads>vsyasm.exe -Xvc -f win64 -i "C:\Users\kuh3h\Downloads\kvazaar\build\..\src\extras" -d "ARCH_X86_64=1" -d "HAVE_ALIGNED_STACK=1" -o "x64-Release\\" -rnasm -pnasm   C:\Users\kuh3h\Downloads\kvazaar\src\strategies\x86_asm\picture-x86-asm-satd.asm

now build ok.

**Comment by Arizer** [comment]
Thanks for reporting!

We haven't tried compiling on 2017, but vsyasm compiles object files at least on 2015 version. Do you have the error message about why vsyasm fails to compile those object files?

**Comment by kuh3h3** [comment]
sorry.  this was my mistake.
changed project vsyasm build customizations to system folder instead of kvazaar local folder.
after clean 
rebuild ok. no problems
