### ISSUE TITLE
Which file to modify to force the QP value of all frames as configured ?

### ISSUE THREAD

**Issue by yibinfan** [ultravideo/kvazaar#180]
Hi,

I have tried encoding the video with -q option to set the QP of frames. However, I found that only the QP of I frames were set as the configuration while the QP of P frames were slightly higher than the configured QP value. For example, if I set QP as 18, the QPs of the P frames may range from 19 to 21 or so.

I was wondering whether I can set all the frames with the same QP value? Could you please give me some hints on which command option should I try or which file should I modify for this goal?

Thanks!

**Comment by fador** [comment]
Hi,

You can set --gop=0 to disable the QP changing.

**Comment by yibinfan** [comment]
It works! 
Many thanks!

**Comment by fador** [comment]
You're welcome =)
