### ISSUE TITLE
Decoding kvazaar output

### ISSUE THREAD

**Issue by OmarEltobgy** [ultravideo/kvazaar#181]
Greetings, 

Would you please tell me how can i decode the kvazaar output file ? 

Also, i tried to play the kvazaar output by vlc player that has already the HEVC decoder but it didn't understand hvc2 and hvt1 codecs
In addition, i tried using ffmpeg and it didn't understand hvc2 and hvt1 codecs too.

My goal is to calculate the psnr and ssim value of the generated hevc video file.

Best Regards,
Omar Eltobgy

**Comment by fador** [comment]
Hi,

Kvazaar output is standard HEVC but some players like VLC do not like the raw bitstream, it should be put e.g. mp4 container using mp4box or ffmpeg.

You should be able to calculate PSNR using ffmpeg like this:
`ffmpeg -pix_fmt yuv420p -s:v 1920x1080 -r 30 -i original_1920x1080.yuv -r 30 -i kvazaar_output.265 -c:v rawvideo -filter_complex "[0:v][1:v]psnr" -f null nul`
just replace `psnr` with `ssim` to get the ssim results.

BR,
Marko
