### ISSUE TITLE
run ./autogen.sh  fail on the ubuntu16.04

### ISSUE THREAD

**Issue by lizhongwang520** [ultravideo/kvazaar#182]
li@li-fzu:~/kvazaar$ ./autogen.sh 
src/Makefile.am:2: error: Libtool library used but 'LIBTOOL' is undefined
src/Makefile.am:2:   The usual way to define 'LIBTOOL' is to add 'LT_INIT'
src/Makefile.am:2:   to 'configure.ac' and run 'aclocal' and 'autoconf' again.
src/Makefile.am:2:   If 'LT_INIT' is in 'configure.ac', make sure
src/Makefile.am:2:   its definition is in aclocal's search path.
autoreconf: automake failed with exit status: 1

**Comment by aryla** [comment]
It looks like you don't have libtool installed.

**Comment by Arizer** [comment]
Is this issue solved?
