### ISSUE TITLE
tile split

### ISSUE THREAD

**Issue by fujunustc** [ultravideo/kvazaar#187]
Hey, could you give some tips to split picture into tiles as shown in this picture?
As i see, the ` --tiles-width-split <string>|u<int> ` and `--tiles-height-split <string>|u<int> ` can not meet the need.
![tile_split](https://user-images.githubusercontent.com/33153297/37013436-d8c5372c-2134-11e8-814c-7f5bbbd96c64.png)

Thank for your time.

**Comment by aryla** [comment]
Unfortunately, Kvazaar does not support such split.

**Comment by fujunustc** [comment]
Thanks!

**Comment by peipeiguo** [comment]
Hi, is there any plan to support this split scheme in Kvazaar? The higher longitude, the less tiles numer. Thanks.
