### ISSUE TITLE
tests_main.c

### ISSUE THREAD

**Issue by jodyngo** [ultravideo/kvazaar#188]
I run file "test_main.c" on VS2015, and it shows below error

Severity	Code	Description	Project	File	Line	Suppression State
Error	C1083	Cannot open include file: 'pthread.h': No such file or directory	kvazaar_lib	f:\video codecs\kvazaar-1.2.0\src\threadqueue.h	29	

Would you please advise above error. I am just a beginner in video encoding so I really need a help for this issue.

**Comment by Arizer** [comment]
Hi,

you are probably missing the pthread library. See "Required libraries" in readme.

**Comment by Arizer** [comment]
Is this issue solved?
