### ISSUE TITLE
ROI-Based rate control, the delta map format

### ISSUE THREAD

**Issue by JesseYang-CQ** [ultravideo/kvazaar#194]
hi, i try to use kvazaar encode the video based on the ROI,  while the document  say that can read an array form a delta QP map during the encoding, my question is which format of delta QP map could Kvazaar support（is .TXT ? or something else）

**Comment by aryla** [comment]
It should be a text file with width and height followed by the QP adjustment. For example,
```
3 3
2 1 0
1 0 1
0 1 2
```

**Comment by JesseYang-CQ** [comment]
Hi aryla, thanks for your help, when i try to use the QP delta map during the encoding, the  problem happens, like this：
Reading ROI file failed.
invalid argument: roi=qpmap1.txt
and my command is like this：
kvazaar --input shortac.yuv --input-res=3840x1920 --erp-aqp  --tiles 3x3 --slices tiles --mv-constraint  frametile   --roi qpmap1.txt  --output aerialtilesv1.hevc
would you mind help to check out what’s wrong with that? Thanks angain.

**Comment by aryla** [comment]
It seems like qpmap1.txt either contains fewer than width times height QP delta values or there is some unrelated data mixed in.

**Comment by JesseYang-CQ** [comment]
hi,aryla, you are right, I had misunderstood about the QP map,  In my situation, I want to ecode the 100 frame of video in the format of HEVC tiles,  my resource video resolution is 3840x1920,  i want encode as 3x3 tiles, and each tile should have different QP, so i try to use the ROI concept,  the width and height of ROI  I set as 1280x640,  as you recommended, does the number of  QP delta values should be 1280x640? which means each pixel should set a target QP value? 
here i also have two questios one  is：if  every video frame have different ROI, how could i set the QP map in the QP map file？ the second one is：QP delta values is the result of  the target QP value minus the default QP value? and what is the default QP value?  thanks

**Comment by aryla** [comment]
> i try to use the ROI concept, the width and height of ROI I set as 1280x640, as you recommended, does the number of QP delta values should be 1280x640? which means each pixel should set a target QP value?

The QP delta map is upsampled to match the size of the video. In your case, you can simply set width and height to 3 and enter 9 QP delta values, one for each tile.

> if every video frame have different ROI, how could i set the QP map in the QP map file？

Unfortunately, Kvazaar currently only supports a single QP map for the entire sequence.

> QP delta values is the result of the target QP value minus the default QP value?

Yes.

> what is the default QP value?

The initial QP can be set with the `--qp` option, which defaults to 22. The frame base QP (before adding the ROI QP delta) for each frame is changed based on the GOP structure. This can be disabled by specifying `--gop=0`.

Note that the `--erp-aqp` flag sets up an additional QP delta map. The final QP for each CTU (64x64 block) is the sum of the frame base QP, the ROI QP delta and the ERP QP delta.

**Comment by JesseYang-CQ** [comment]
dear aryla, thank you so much for your help, for the --erp-aqp , my 360 video is used ERP projection format, what if i set nonerp-aqp during the encoding, do it still add the ERP QP delta? how did the kvazzar conculate the ERP QP delta value?

**Comment by JesseYang-CQ** [comment]
another question is that i saw the introduction at gpac website: https://gpac.wp.imt.fr/2017/02/01/hevc-tile-based-adaptation-guide/, "You will need to package your raw HEVC bitstream with MP4Box, instructing it to split the tiles of each frame in different tracks, using the :split_tiles import switch"   which confused me is that when i use the kvazzar encode the 360 video into tile format, so the encoded video is one bitstream,  use the MP4box to split the tile tracks which mean all the tile track is become independent？ is my understand right or not?

![20180322](https://user-images.githubusercontent.com/25653091/37768128-82099f1a-2e07-11e8-9f09-bc4473d80a5f.jpg)

**Comment by aryla** [comment]
> if i set nonerp-aqp during the encoding, do it still add the ERP QP delta?

No, it's only used when `--erp-aqp` is given.

> how did the kvazzar conculate the ERP QP delta value?

In ERP video, the ratio of the covered viewing angle and the number of pixels is highest for the middle part and gets smaller toward the top and bottom. `--erp-aqp` compensates this by using more bits (lower QP) for the middle part and less bits (higher QP) for the top and bottom. See [JVET-F0049](http://phenix.it-sudparis.eu/jvet/doc_end_user/current_document.php?id=3073)

> all the tile track is become independent？

I'm not familiar with MP4Box but it's possible to make the tiles independently decodable. You would need to use `--mv-constraint=frametilemargin` instead of `--mv-constraint=frametile`, however.
