### ISSUE TITLE
How to tile with kvazaar??

### ISSUE THREAD

**Issue by JamesXu20150314** [ultravideo/kvazaar#195]
Hello,
How to tile with kvazaar?

Here is my command:
kvazaar --input test.yuv --tiles-width-split 0,240,480,720 --tiles-height-split 0,240,480 --slices tiles --mv-constraint frametilemargin --output out_3x4.hevc

However, the problem is:

![image](https://user-images.githubusercontent.com/11470231/37710886-028c24fa-2d4a-11e8-8d27-808ae907dead.png)

Thank you

**Comment by Arizer** [comment]
Hi,

you should drop the zeroes in front of the lists. Also, the numbers need to be multiples of 64.
If you really want to set these manually, you may do this: 
--tiles-width-split 256,512,768 --tiles-height-split 256,512

Using the u notation is easier though, since your tiles are the same size:
--tiles-width-split u4 --tiles-height-split u3
this splits the frame into 3x4 tiles of equivalent size (if possible)

**Comment by JamesXu20150314** [comment]
Thank you very much.

**Comment by sdancer75** [comment]
In the parameteres list the kvazaar encoder says this 

> Wavefront parallel processing.
>                                Enabling tiles automatically disables WPP. To
>                                enable WPP with tiles, re-enable it after
>                                enabling tiles. [enabled]

This means the encoder is able to do Parallel encoding using WPP and Tiles simultaneously ? I thought this was an incompatible mode.

**Comment by JamesXu20150314** [comment]
Hi @Arizer  ,
 I want to know that how to use kvazaar and GPAC to generate multi-rate tiles in one MPD files, such as this file ([http://download.tsi.telecom-paristech.fr/gpac/SRD/srd_hevc/multi_rate_p60/hevc_srd.mpd](http://download.tsi.telecom-paristech.fr/gpac/SRD/srd_hevc/multi_rate_p60/hevc_srd.mpd)).

As the “base tile track” and xx_set1_init.mp4 only contains one bitrate level's parameters. 

I can not generate the multi-rate MPD by modifying the different bitrate level's MPD respectively.

Thanks.

**Comment by Arizer** [comment]
Hi,

This might be helpful: [https://github.com/gpac/gpac/wiki/Tiled-Streaming](https://github.com/gpac/gpac/wiki/Tiled-Streaming)

Single MPD with multiple representations is covered there as well.
