### ISSUE TITLE
Does kvazaar supports only YUV video as input?

### ISSUE THREAD

**Issue by mdasari823** [ultravideo/kvazaar#196]
I was wondering the encoder supports only YUV format as input. When I encode an MP4 file, I get garbage output playback.

**Comment by Arizer** [comment]
Hi,

Only yuv formats (4:2:0 and 4:0:0, 8 bit and 10 bit) are supported at the moment.

**Comment by Arizer** [comment]
...and 10 bit coding requires changing the KVZ_BIT_DEPTH before compiling
