### ISSUE TITLE
WPP and Tiles encoding

### ISSUE THREAD

**Issue by sdancer75** [ultravideo/kvazaar#201]
In the parameteres list the kvazaar encoder says this

> Wavefront parallel processing.
> Enabling tiles automatically disables WPP. To
> enable WPP with tiles, re-enable it after
> enabling tiles. [enabled]

This means the encoder is able to do Parallel encoding using WPP and Tiles simultaneously ? I thought this was an incompatible mode.

**Comment by Arizer** [comment]
That is true as far as I know. This is pretty much an experimental feature at the moment. I recall there was a (tiny) chance that a profile could have been added to HEVC that allows the co-operation of tiles and wpp. Parallelism in Kvazaar was implemented in a way that required practically no changes to enable this feature, so it was. Why it isn't marked as an experimental or non-standard feature on the help, I do not know.

**Comment by sdancer75** [comment]
Thanks !

**Comment by Arizer** [comment]
Added comment in 2bc4594
