### ISSUE TITLE
Directory visualizer_extras is missing

### ISSUE THREAD

**Issue by sdancer75** [ultravideo/kvazaar#202]
> Directory visualizer_extras is expected to be found from the same directory level as the kvazaar project directory

I didn't see anything !

**Comment by Arizer** [comment]
Hi, did you clone the visualizer branch?

**Comment by Arizer** [comment]
Ok, I think there might have been some misunderstanding about that folder. It is up to the user to create it and add the include and lib folders that are specified in the instructions (SDL2 and SDL2-ttf, links are found in the Visualizer instructions).

**Comment by Arizer** [comment]
Also, be aware that all the recent fixes are not yet applied on the visualizer branch, you might need to add HAVE_STRUCT_TIMESPEC define for the kvazaar_cli and kvazaar_lib.

**Comment by sdancer75** [comment]
thanks I didnt realized this.... but I dont think that the instructions are very clear on that. 

Thanks

**Comment by Arizer** [comment]
You're welcome. The instructions are indeed a bit ambiguous.

**Comment by Arizer** [comment]
Tried to make the instructions a bit clearer in f9463d0
