### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by L3MOJOHA5HTAG** [ultravideo/kvazaar#203]
I'm getting this message while compiling

Cannot open include file: 'pthread.h': No such file or directory

I extracted pthreads.2 folder to /kvaazar directory

**Comment by Arizer** [comment]
Hi,

The pthreads.2 folder needs to be in the same directory where the kvazaar folder is located.

**Comment by L3MOJOHA5HTAG** [comment]
Hi,

Thanks. I did that and now the error is due to something on pthreads.h. Do I need to use a specific version of it?

Ali Naisaan

**Comment by Arizer** [comment]
What kind of error?

The newest pthreads-win32 version should be fine.

**Comment by Arizer** [comment]
Did you manage to compile Kvazaar?

**Comment by L3MOJOHA5HTAG** [comment]
Naa. I didn't try after that. Got busy with other stuff. I'll do and notify
about any errors. Or a screenshot of the order might be helpful, perhaps.

**Comment by tnti** [comment]
Compiling Kvazaar in Visual Studio2017

1. First need to download kvazaar source code and greatest source code
Git clone https://github.com/ultravideo/kvazaar.git kvazaar
Git clone https://github.com/ultravideo/greatest.git kvazaar//greatest

Copy the greatest source to the corresponding folder in kvazaar

2. Download pthreads-w32-2-9-1-release.zip to ftp://sourceware.org/pub/pthreads-win32
Unzip into the Pre-built.2 folder
Copy the three files in the include folder to *:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.14.26428\include

Copy pthreadVC2.lib from the lib folder to build\kvazaar_lib. Note that it corresponds to the compiled version. 64-bit X64 32-bit X86

3. Then go to http://yasm.tortall.net/Download.html to download the corresponding version of vsyasm, Win32 VS2010 .zip or Win64 VS2010 .zip
Decompression
Put win32's vsyasm.exe in *:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.14.26428\bin\Hostx86\x86
Put Win64's vsyasm.exe in *:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.14.26428\bin\Hostx86\x64
Put vsyasm.props, vsyasm.targets, vsyasm.xml in C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\BuildCustomizations

4. After compiling, you need to copy pthreadVC2.dll from pthreads-w32-2-9-1-release\Pre-built.2\dll to kvazaar.exe directory.
Need to pay attention to the corresponding version of the 64-bit X64 32-bit X86
Finally run kvazaar.exe

Machine translation may be wrong

**Comment by schwicko** [comment]
Thanks for this detailed tutorial, which I followed step by step, since I'm not that experienced in C. My visual studio version is 2017 (community).
I still got compilation errors when compiling the kvazaar_cli.
I created the kvazaar_lib.lib successfully, which now is located at ..\kvazaar-master\build\x64-Debug-libs.

When I try compiling the kvazaar_cli I always get: 

Error LNK2019	unresolved external symbol  "__imp_pthread_create" in function "main".	kvazaar_cli	...\kvazaar-master\build\kvazaar_cli\encmain.obj	1	
Error LNK2001	unresolved external symbol "__imp_pthread_create".	kvazaar_cli	..\kvazaar-master\build\kvazaar_cli\kvazaar_lib.lib(threadqueue.obj)	1	

many more errors for i.a.:
"__imp_pthread_exit" in Funktion "input_read_thread"
 "__imp_pthread_join" in Funktion "main".	
"__imp_pthread_join".	
"__imp_sem_init" in function "kvz_sem_init".
	
leading to error
LNK1120	16 unresolved token kvazaar_cli	..\kvazaar-master\bin\x64-Debug\kvazaar.exe	1	

I set the vsyasm build costumizations per right click in VisualStudios accordingly and copied all the files, according to the describtion above. I tried replacing the x32 versions to x64 and tried again, without success.
Thanks for your help!

**Comment by fador** [comment]
@schwicko it sounds like it does not find and link pthreadVC2.lib, do you have the correct version (32bit/64bit) in the correct place..?

**Comment by schwicko** [comment]
I put the pthreadVC2.lib into to the /build/kvazaar_lib. I took the x64 version, as my compiling is in x64, besides I tried the same with the x32 lib, just to be save. The three items of the include folder of Pre-built.2 I copied to C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include. Do these files need to be present at another level/location?

As described in the git tutorial:
"For Visual Studio, the pthreads-w32 library is required. Platforms with native POSIX thread support don't need anything.
- The project file expects the library to be in ../pthreads.2/ relative to Kvazaar. You can just extract the pre-built library there."

I also moved a Copy of the file pthreadVC2.lib into a folder named /pthreads.2 at the build/kvazaar_lib level, just to test. I copied this folder to other levels of my kvazaar folder, as well as the single pthreadVC2.lib at other locations, like /x64-Debug-libs or /kvazaar_cli, just to be save, that the link does not refer to other locations. No changes to my error log, still got 19 errors in kvazaar_lib.lib and encmain.obj.

**Comment by schwicko** [comment]
Thanks @fador I think I found the problem. When I created the kvazaar_lib.lib I didn't copy the pthreads.2 folder to the same level as my kvazaar main folder, but into it. It looks like my first kvazaar_lib.lib file was incorrect, which I always used afterwards. 

I started from new, creating a new kvazaar_lib.lib with the pthread links at the right locations and got my .exe out of the kvazaar_cli compilation. Wouldn't it be useful to provide this build, so others using win10 don't need to compile it from new?

**Comment by fador** [comment]
You're welcome @schwicko!
We were suppose to look into providing binaries at release, but it seems our release schedule has been moved a bit. I try to make sure we release the windows binaries for the release =)
Also we are looking into the pthreads-win32 dependancy, it seems to be a problem for many windows users..

**Comment by vtorri** [comment]
is this issue still valid with the latest code ?

**Comment by fador** [comment]
@vtorri good point, it is not.
We replaced win32 pthreads with our own implementation, so this should not be an issue anymore. I'm closing this.
