### ISSUE TITLE
--owf:  encode N-1 frames at the same time

### ISSUE THREAD

**Issue by luismacostero** [ultravideo/kvazaar#204]
Hi!,

In the README file, it says:
```
    --owf <integer>        : Frame-level parallelism [auto]
                                       - N: Process N-1 frames at a time.
                                       - auto: Select automatically.
```

But doing some experiments, I think it should be N+1, instead of N-1.
Can you confirm me if the readme file is wrong, or there's a problem on my experiments?

Thanks in advance!

**Comment by aryla** [comment]
You're right, it should indeed be N+1. Thank you for reporting this!
