### ISSUE TITLE
1x1 tile encoding hvc  file size is x8 larger. 

### ISSUE THREAD

**Issue by shkp4j** [ultravideo/kvazaar#208]
I am encoding hevc in 1x1 tile, and the file size is x8 larger than other tile encodings (e.g. 6x4 files). 
Can someone please help what went  wrong in this command? 

kvazaar -i  outputfile.yuv --input-res 3840x1920  -o output.hvc --input-fps 30 -p 15 --bitrate 2000000 --tiles 1x1 --slices tiles --mv-constraint frametilemargin

kvazaar -i  outputfile.yuv --input-res 3840x1920  -o output.hvc --input-fps 30 -p 15 --bitrate 2000000 --tiles 6x4 --slices tiles --mv-constraint frametilemargin

Thank you for your help.

**Comment by Arizer** [comment]
Hi,

This is probably a bug related to rate control and lp-gop (which is enabled by default). After quick experimenting, it seems that Kvazaar is using more and more bits per frame over time. Try adding option --gop=0, as it seems to get rid of that behaviour.

(Also, you might want to check if image quality is acceptable, the bitrate may be a bit low for 4k.)

Hope this helps!

**Comment by Jovasa** [comment]
Should be fixed in b71c5573f072b7361b612fed5a08c3d20cda9133
