### ISSUE TITLE
[tests] test_external_symbols.sh fails to run when building with cryptopp enabled

### ISSUE THREAD

**Issue by dbermond** [ultravideo/kvazaar#215]
I'm getting the following error when running the tests with cryptopp enabled:

- [https://bpaste.net/show/f94d73136a07](https://bpaste.net/show/f94d73136a07)
- [test-suite.log](https://bpaste.net/show/c457cbf4a407)

Submodule greatest is checked-out and initialized/updated. The building commands can be found on the first link above.

All tests passes when building _without_ cryptopp.

**System Information:**
**OS:** Arch Linux x86_64
**kvazaar:** git master
**Compiler:** gcc 8.2.1
**yasm:** 1.3.0
**HM:** 16.20
**glibc:** 2.28
**crypto++:** 7.0.0

**Comment by dbermond** [comment]
The logs on the above links have expired, since bpaste does not provide permanent pastes anymore.

Here is a new [test-suite.log](https://linkode.org/#gK8f2YmeAKBPXFEL9ZgUW3) file.

The error is still present in the current kvazaar git master. Now using crypto++ 8.2.0.

**Comment by Arizer** [comment]
Thanks for the update. Will discuss with the team.

**Comment by moptim** [comment]
Should be fixed now in 75b25955fa401d857c98ea55ad837415179f02c3

**Comment by dbermond** [comment]
I can confirm that commit https://github.com/ultravideo/kvazaar/commit/75b25955fa401d857c98ea55ad837415179f02c3 fix this issue.

test_external_symbols now xfail when building with crypto++ enabled, and the test suite passes.

Thank you for fixing this!
