### ISSUE TITLE
Too big file size for few tiled HEVC DASH segments !!!

### ISSUE THREAD

**Issue by 21praveen** [ultravideo/kvazaar#220]
Hi,

I am trying to create tiled DASH segments using kvazaar and GPAC's MP4Box. The video is segmented and playing well. But there is an issue with file size. 
When I check the total size of a segment (sum of file size for all the tiles), for two particular segments, the size is almost 10 times of the expected value (10 times of segment duration * total_bitrate). Although the file size is approximately equal to segment duration * total_bitrate for other segments. I tried various options to control the size like  --no-erp-aqp/--gop lp-g30d1t1/ --level 5 --preset veryslow/ --gop 0 etc.  But nothing worked. The video resolution is 3840x2048 with the frame rate of 30.  
With different combination of above-mentioned options, the segment number for the file with the extraordinary size are different. But there are always two such segments. 

The encoding parameters used ae as follows: 
kvazaar --input '/media/SRD/uncompressed/CBR_3840x2048_30fps_420_8bit_YUV.yuv' --input-fps 30 --no-erp-aqp --gop lp-g30d1t1 --level 5 --preset veryslow --threads 4 --tiles 6x4 --slices tiles --mv-constraint frametilemargin --bitrate 1000000 --output '/media/SRD/chk/out1.hevc'

MP4Box -add '/media/SRD/chk/out1.hevc':FMT=HEVC:split_tiles -new '/media/SRD/chk/video_tiled1.mp4'
    
MP4Box -dash 2000 -profile live -out '/media/SRD/chk/a.mpd'  '/media/SRD/chk/video_tiled1.mp4'

The two segments are causing a big stall while doing rate adaptation at DASH client. Any suggestions, what might be going wrong?

**Comment by Jovasa** [comment]
Should be fixed in b71c5573f072b7361b612fed5a08c3d20cda9133

**Comment by 21praveen** [comment]
@Jovasa Thank you for replying. 

When can I expect b71c557 to be released?

**Comment by Jovasa** [comment]
It is available on the current master branch.
