### ISSUE TITLE
Questions about encoder video input

### ISSUE THREAD

**Issue by YanjunHH** [ultravideo/kvazaar#221]
Hi，How to set live video as input to the encoder？I want to implement the process as shown.Can you give me some suggestions and details on how to modify the encoder？ Thank you~
![image](https://user-images.githubusercontent.com/37657848/50438572-7e5f6180-0929-11e9-84f2-2cdcf2f124a1.png)

**Comment by fador** [comment]
Sorry for the delay!

So what usually do is pipe the input through stdin, which is supported in kvazaar by default, just give `--input -` or `-i -` as the input parameter.

#### Windows:
Use `ffmpeg -f dshow -list_devices 1 -i dummy` to get list of cameras, example with a webcam:
```
ffmpeg -f dshow -s 1920x1080 -framerate30 -i video="Logitech Webcam C930e"  -f rawvideo -pix_fmt yuvj420p - | kvazaar -i - --input-res=1920x1080 --preset=ultrafast -o output.hevc
```

#### Linux:
Those AV.io 4k capture cards show up as /dev/video? devices, so they can be used like this:
```
ffmpeg -f v4l2 -framerate 30 -video_size 3840x2160 -i /dev/video0 -an -f rawvideo -pix_fmt yuvj420p - | kvazaar -i - --input-res=3840x2160 --preset=ultrafast -o output.hevc
```

**Comment by YanjunHH** [comment]
Thank you fador , these are very useful to me.
Have you ever had this problem?
![image](https://user-images.githubusercontent.com/37657848/50831261-3eff2f00-1385-11e9-8a71-4f9a8247e610.png)

**Comment by fador** [comment]
Not a familiar problem for me, I would think that's because the input device does not support more than 10fps with the given (or default) format. For some webcams you need to specify the output format, like `-c:v mjpeg` before `-i /dev/video1`
