### ISSUE TITLE
new release ?

### ISSUE THREAD

**Issue by vtorri** [ultravideo/kvazaar#229]
hello

last release was 1 year and a half. Is a new release planned soon ?

thank you

**Comment by fador** [comment]
Yes, thank you for reminding! @Arizer was planning on making the release in the next two weeks or so.

**Comment by fador** [comment]
Well, it has taken longer than expected, but @Arizer was saying that the release might be ready next week

**Comment by Arizer** [comment]
Version 1.3.0 has been just released (5db3a784). Binaries and more release notes will added in the following days.

Cheers!

**Comment by vtorri** [comment]
thank you
