### ISSUE TITLE
unresolved external symbol _kvz_satd_8x8_avx, referenced in function xxxxxxxxxx

### ISSUE THREAD

**Issue by HikariS97** [ultravideo/kvazaar#230]
![QQ截图20190702180822](https://user-images.githubusercontent.com/48763518/60504608-7b886380-9cf4-11e9-89b9-3e92eb7a5c9e.png)
Can someone help me with this problem ? It appears when compling kvazaar_cli.
Before this problem I have encountered one " cannot open 'kvazaar_lib.lib' " and "cannot open input file 'xxxxxxx\.picture-x86-asm.obj' ".

**Comment by fador** [comment]
Hi,
Do you have vsyasm.exe in some folder in PATH? ( http://www.tortall.net/projects/yasm/releases/vsyasm-1.3.0-win64.zip )
It sounds like it doesn't compile the .asm files..

**Comment by HikariS97** [comment]
> Hi,
> Do you have vsyasm.exe in some folder in PATH? ( http://www.tortall.net/projects/yasm/releases/vsyasm-1.3.0-win64.zip )
> It sounds like it doesn't compile the .asm files..

C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\Hostx86\x86

yes, i have that. I have saw a instruction in someone's blog that if the number behind the VS in task manager is 32, then I have to download 32bit version. But my computer is 64bit, so I drag both 32bit and 64bit vsyasm.exe in to folder respectively.

**Comment by fador** [comment]
It might have to be in \bin\Hostx64\.. to work..
My solution was to put the vsyasm.exe to c:\mybins\ and edit Environment Variable "Path" to include this directory, also you need to restart the visual studio after doing this.

**Comment by HikariS97** [comment]
I have followed your instruction and added the Environment, but I also get the errors. omg.

**Comment by HikariS97** [comment]
I have checked the folder, and find the .obj file right in there.
![QQ截图20190703210124](https://user-images.githubusercontent.com/48763518/60593673-d8a81600-9dd5-11e9-884c-2a0225269265.png)

I have also checked the Environment Variable. I typed 'vsyasm.exe' in powershell and get ' no input file' as result. Please give me more clues about the error, thanks a lot !

**Comment by HikariS97** [comment]
> Hi,
> Do you have vsyasm.exe in some folder in PATH? ( http://www.tortall.net/projects/yasm/releases/vsyasm-1.3.0-win64.zip )
> It sounds like it doesn't compile the .asm files..

I have got the same error as metioned in #189 , and I still get the error after instruction. "Cannot open input file 'picture-xxxxxx-sad.obj'"

**Comment by HikariS97** [comment]
Here are some screenshots.
![QQ截图20190704222740](https://user-images.githubusercontent.com/48763518/60673756-132fb280-9eab-11e9-9d97-054ad58b481b.png)
![QQ截图20190704222753](https://user-images.githubusercontent.com/48763518/60673758-13c84900-9eab-11e9-8908-90423eebc866.png)
![QQ截图20190704222826](https://user-images.githubusercontent.com/48763518/60673759-13c84900-9eab-11e9-9cb1-5f4201fe81b8.png)
