### ISSUE TITLE
compilation error with the 1.3 release

### ISSUE THREAD

**Issue by vtorri** [ultravideo/kvazaar#233]
here it is : 

image.h:32:10: fatal error: strategies/optimized_sad_func_ptr_t.h: No such file or directory

**Comment by vtorri** [comment]
the file is in git but not in the tarball

note that to be sure that everything is in the tarball, run 'make distcheck'

**Comment by Arizer** [comment]
Thanks for letting us know. I'll try to have a look at this tomorrow and let you know when it is fixed.

**Comment by Arizer** [comment]
Updated tarballs are now available with the missing headers.

Make distcheck runs with (most of) the tests passing. I added this step to our release checklist so this should not happen again. Tried and compiled Kvazaar from the tarball succesfully.

Hopefully there are no other critical issues.

**Comment by Arizer** [comment]
Closing the issue since this should be ok. Feel free to open again if something comes up.
