### ISSUE TITLE
reg_sad_pow2_widths_sse41.h

### ISSUE THREAD

**Issue by HikariS97** [ultravideo/kvazaar#234]
many faults iwhen compiling kvazzar_lib.
like "_mm_set1_epi64x":  intrinsic function not declared
 cannot convert from "" to "const_m128i"
![微信截图_20190712165849](https://user-images.githubusercontent.com/48763518/61116140-71b9e980-a4c6-11e9-9b6f-bcb30a388d7b.jpg)
![微信截图_20190712165921](https://user-images.githubusercontent.com/48763518/61116145-7383ad00-a4c6-11e9-8048-ffe333c9dd02.jpg)

**Comment by fador** [comment]
Hi,

You are using the  Visual Studio 2017?
Can you try if "x64" build works?
There seems to be some problems with the win32, but in my VS2017 it still seems to compile. We have the enterprise edition in use.

**Comment by HikariS97** [comment]
Yes I have tried but failed. It seems ver1.3 doesn’t like my computer. I have turned to ver1.2 and the error timespec appeared. I fixed it up but haven’t tested yet
