### ISSUE TITLE
How to control bitrate?

### ISSUE THREAD

**Issue by liudongbo** [ultravideo/kvazaar#235]
I set some paraments like -bitrate 500000, but there not exist actual bitrate in output.
Any parameters can output the actual bitrate?

**Comment by Arizer** [comment]
Hi,

Sorry for the delay. Kvazaar does not currently output the bitrate (as you noticed). However, this feature has already been worked on in a feature branch, but unfortunately it is not finished and no one is currently working on it. I'll try to get someone to finish it in the early autumn.

**Comment by Arizer** [comment]
I started to think that you might not be talking about the text output.

In case you are saying that the output video does not have the correct bitrate:

1) Long options in Kvazaar have 2 dashes in front of them. Use "--bitrate" and not "-bitrate"
2) The frame rate needs to be set to correct value. The default is "--input-fps 25".
3) Bitrate does not work very well in some cases.
