### ISSUE TITLE
Whether Kvazaar support QP dynamic adjustment?

### ISSUE THREAD

**Issue by peipeiguo** [ultravideo/kvazaar#251]
Hi all,

About setting QP, I just learned Kvazaar have two methods:
1. Through `--qp` parameter, all frames will have same QP specified.
2. Through `--roi` parameter, can specify different QP (LCU level) in one frame, but same style all frame.

Whether Kvazaar support QP dynamic adjustment (each frame separately)? Such as based on ROI area and non-ROI area, or adaptive QP based on the frame content. Scenario is for VR 360. Is there anyone who know how to do?

Thanks.

**Comment by Jovasa** [comment]
This is something that we have done in the past internally, I have published the branch here in github `roi-picture`. However be aware that it is highly experimental and may break easily.

There is a parameter called `--roi-file`  that takes a binary file that consists of the RoI in a similiar fashion as the `--roi` parameter except that there is separate data for each frame, and again it is a binary file. You can check out the file reading [here.](https://github.com/ultravideo/kvazaar/blob/9e218224618c9f3f59c9582bb3b0b6a03af02b0f/src/encmain.c#L240) 

If you have any further questions I am happy to help and I may be able to change the input format to something that suits you better.

**Comment by ChaeSeoyoung** [comment]
I cloned roi-frame branch, and when adding `--roi-file` to kvazaar command, it says `kvazaar: unrecognized option '--roi-file'`

Should I use `--roi` parameter? or how can I use `--roi-file` parameter?

**Comment by Jovasa** [comment]
Sorry for not answering earlier but there has also been internally again need for this and updated version of the `roi-frame` branch is likely going to be merged to the master branch sometime next week.

**Comment by Jovasa** [comment]
The roi features are now merged to the master and the new functionality of the `--roi` command is now following:
```
--roi <filename>             : Use a delta QP map for region of interest.
                               Reads an array of delta QP values from a file.
                               Text and binary files are supported and detected
                               from the file extension (.txt/.bin). If a known
                               extension is not found, the file is treated as
                               a text file. The file can include one or many
                               ROI frames each in the following format:
                               width and height of the QP delta map followed
                               by width * height delta QP values in raster
                               order. In binary format, width and height are
                               32-bit integers whereas the delta QP values are
                               signed 8-bit values. The map can be of any size
                               and will be scaled to the video size. The file
                               reading will loop if end of the file is reached.
                               See roi.txt in the examples folder.
```
