### ISSUE TITLE
No B-frame found in hevc

### ISSUE THREAD

**Issue by LeoKingLong** [ultravideo/kvazaar#252]
I make an hevc file from yuv by the command ：
--input-res 7680x3840 --tiles 3x3 --slices tiles --no-open-gop --bitrate 60000000 --period 30  --threads 40 --mv-constraint frametilemargin

,but  when I analysis the  generated hevc file , I  only found I-frames and P-frames , no B-frame in the hevc file.
Could you tell me which parameter to control the B-frame ？ 
Thanks.

**Comment by Jovasa** [comment]
B-frames are enabled and disabled by the parameters `--bipred` and `--no-bipred`, respectively.

**Comment by LeoKingLong** [comment]
Thanks
