### ISSUE TITLE
Grayscale Video Sequences Encoding and Real-Time Encoding

### ISSUE THREAD

**Issue by HikariS97** [ultravideo/kvazaar#253]
Hi.
Recently I've got an idea to enable kvazaar to encoding grayscale video more than format yuv420p and encode frames real-time. Could you give some advices about where to start on, or whether it's feasible? 
I will be glad to get any reply. Thank you.

**Comment by fador** [comment]
Hi,

You should be able to encode grayscale video using `--input-format=P400`
It does, however, require grayscale input, so if you want to use yuv420p, it has to be converted to grayscale first.
Or was this the thing you want to implement inside Kvazaar..?

Realtime encoding should be possible with `--preset=ultrafast`, depending on the CPU etc..

If I missed something, just ask for more details =)

-Marko

**Comment by HikariS97** [comment]
> Hi,
> 
> You should be able to encode grayscale video using `--input-format=P400`
> It does, however, require grayscale input, so if you want to use yuv420p, it has to be converted to grayscale first.
> Or was this the thing you want to implement inside Kvazaar..?
> 
> Realtime encoding should be possible with `--preset=ultrafast`, depending on the CPU etc..
> 
> If I missed something, just ask for more details =)
> 
> -Marko

Sorry for replying so late and thanks to your patience. I mean how to integrate kvazaar into a video streaming pipeline. I don't mean to encode N frames(fps) in a second. Someone had developed a gstreamer plugin for kvazaar, and I want to know if it is  a official implement or some other methods to integrate kvazaar into a pipeline.
