### ISSUE TITLE
Does kvazaar support random access (RA)  coding configuration?

### ISSUE THREAD

**Issue by zhao-l13** [ultravideo/kvazaar#256]
In your paper, it said kv supported HEVC coding configurations including all-intra(AI), random access (RA), and low-delay P (LP). I found the setting options for  all-intra(AI) and low-delay P (LP). I did not find the random access (RA) option. 
I want to set  random access (RA) option and here to confirm whether kvazaar support it or any plan to support it?
Thanks very much!
LULU

**Comment by Arizer** [comment]
Hi,

RA is used with --gop=8 and --gop=16

Maybe we should to add this to readme

**Comment by Arizer** [comment]
...and low-delay with B slices is enabled with --bipred if a low-delay configuration has been set, even though the "lp" GOP definition suggests otherwise.

**Comment by zhao-l13** [comment]
Thank you for your reply.
