### ISSUE TITLE
-p parameter  means I-frame or IDR-frame in closed-gop?

### ISSUE THREAD

**Issue by LeoKingLong** [ultravideo/kvazaar#258]
Test command:
kvazaar.exe --input  input.yuv --cpuid --input-fps 30 --bitrate 10000000 --period 5 --preset ultrafast --erp-aqp --high-tier --level 6.0 --input-res 3840x1920 --no-open-gop --gop lp-g30d1t1 --tiles 1x6 --slices tiles --mv-constraint frametilemargin --output gop30_I5.hevc

 If I use the  command above to make a hevc file,  is the every fifth frame  I-frame or IDR-frame?
Thanks!

**Comment by Arizer** [comment]
Hi,

The intra frames are IDR when closed gop (--no-open-gop) is used. So, every fifth frame should be IDR. If you need to confirm other things about the bitstream, YUView is pretty excellent tool that is  also able to show useful information like NAL unit types of frames. 

Off-topic: some of the options seem suspicious:
* --cpuid is usually only used to disable optimizations, and in that case it takes value 0 (--cpuid=0)
* the lp-gop definition has length of 30, but the intra period limits the actual GOP length to 5

**Comment by LeoKingLong** [comment]
Thank you very much~~
