### ISSUE TITLE
Which parameter decide Profile?

### ISSUE THREAD

**Issue by LeoKingLong** [ultravideo/kvazaar#259]
Which parameter decide Profile?

For example，Main Profile, Main 10 profile or Main Still Picture profile.....

Thanks!

**Comment by Arizer** [comment]
Hi,

Main is the default profile.

Main10 is enabled if a 10-bit version of Kvazaar is compiled (KVZ_BIT_DEPTH needs to be changed to 10 in kvazaar.h).

Kvazaar does not actually signal Main Still Profile in the bitstream, but all-intra coding is used by setting intra period to 1 (--period=1 or -p1).

https://github.com/ultravideo/kvazaar/blob/3eb07005a234b1bcce00a51701aaf4b6110a37c1/src/encoder_state-bitstream.c#L65-L66

**Comment by LeoKingLong** [comment]
Thanks very much~~
