### ISSUE TITLE
32bit broken with mingw32? 

### ISSUE THREAD

**Issue by ASopH** [ultravideo/kvazaar#260]
16:47:49 Running git update for kvazaar...
16:47:50 ┌ kvazaar git .............................. [Recently updated]
16:47:50 ├ Running autogen...
16:48:14 ├ Running configure...
16:48:51 ├ Running make...
Likely error (tail of the failed operation logfile):
Making all in src
make[2]: Entering directory '/build/kvazaar-git/build-32bit/src'
GEN kvazaar.exe
F:/m-a-s/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/9.3.0/../../../../i686-w64-mingw32/bin/ld.exe: ./.libs/libkvazar.a(libavx2_la-picture-avx2.o):picture-avx2.c:(.text+0x8af): undefined reference to `_mm_cvtsi128_si64'
collect2.exe: error: ld returned 1 exit status
make[2]: *** [Makefile:1004: kvazaar.exe] Error 1
make[2]: Leaving directory '/build/kvazaar-git/build-32bit/src'
make[1]: *** [Makefile:524: all-recursive] Error 1
make[1]: Leaving directory '/build/kvazaar-git/build-32bit'
make: *** [Makefile:394: all] Error 2

logs from media autobuild suite ..
[logs.zip](https://github.com/ultravideo/kvazaar/files/4431951/logs.zip)

**Comment by Arizer** [comment]
Hi and thanks for the report.

The issue was also reported by our CI tests here and I would expect that this is fixed early in the next week.

**Comment by Arizer** [comment]
The issue seems to have been fixed.

**Comment by ASopH** [comment]
Hi, thanks for the quick response 👍
