### ISSUE TITLE
Tile this case

### ISSUE THREAD

**Issue by Daktm** [ultravideo/kvazaar#271]
Hi kvazaar,
   I am a freshman for video developer. How to tile a hevc video to this space.
![image](https://user-images.githubusercontent.com/20082687/85388637-e6bbed00-b578-11ea-8cf7-87cc1b91c4de.png)

**Comment by Arizer** [comment]
Hi,

you should use option `--tiles 3x3`

**Comment by Daktm** [comment]
Thanks,
  how to convert output file like this format.
![image](https://user-images.githubusercontent.com/20082687/85400346-d876cc80-b58a-11ea-946d-6f2e2cd85228.png)

**Comment by Arizer** [comment]
Need more info. What exactly are you trying to do? Some kind of adaptive streaming, I guess.

Anyway, this might be useful for you: https://github.com/gpac/gpac/wiki/Tiled-Streaming
