### ISSUE TITLE
About install

### ISSUE THREAD

**Issue by RoyE3BBB** [ultravideo/kvazaar#274]
i dont know how to add it into ffmpeg exactly, thanks

**Comment by Arizer** [comment]
Hi,

It has been vacation season here, hence the late reply. Did you solve the issue yet?

**Comment by RoyE3BBB** [comment]
no, actually

**Comment by Arizer** [comment]
For Windows, there is this handy tool that is able to build FFmpeg with Kvazaar support: https://github.com/m-ab-s/media-autobuild_suite . It is recommended to select the clang compiler during the process to enable AVX2 optimizations in Kvazaar.

On Linux, Kvazaar needs to be installed first (`sudo make install`, like in the README). When building FFmpeg, it needs to be configured with `./configure --enable-libkvazaar` before running `make`.
