### ISSUE TITLE
[Feature request] Support for y4m inputs

### ISSUE THREAD

**Issue by 1480c1** [ultravideo/kvazaar#276]
Would it be possible to add y4m input support for the standalone encoder application or would you be willing to accept patches related to adding support for it?

One benefit of y4m is you wouldn't need to specify width and height etc

https://wiki.multimedia.cx/index.php/YUV4MPEG2

**Comment by Arizer** [comment]
Hi,

Someone is taking a look at this since this is fairly simple. In general, we are happy to receive pull requests.

And by the way, Kvazaar infers the resolution from the file name if it is present, e.g. "something_1920x1080_something.yuv".

**Comment by 1480c1** [comment]
Oh, I didn't know about the resolution from filename part, I now see it in the help option https://github.com/ultravideo/kvazaar/blob/54f438a75cf2d33b056066701161ed0aac31df57/src/cli.c#L349-L351

**Comment by RichardLamm** [comment]
Hi,

Kvazaar does now support y4m as input format. It can be detected from the file ending or forced with "--input-file-format y4m".

**Comment by 1480c1** [comment]
Thanks!
