### ISSUE TITLE
Using on a VPS

### ISSUE THREAD

**Issue by NandiyaLive** [ultravideo/kvazaar#280]
Can I use this on a VPS?

**Comment by fador** [comment]
Hi,
Sure! Our LGPL license allows that kind of use just fine without much limitations..
Do you have any specific use case?
You can just compile Kvazaar and use it as such or compile it with ffmpeg allowing wider range of inputs and outputs.
We actually provide a relatively simple [cloud encoder framework](https://github.com/ultravideo/cloud-encoder) using Kvazaar, although most people might want to customize the system for private use.

**Comment by NandiyaLive** [comment]
Okay thanx :)
