### ISSUE TITLE
KVZ_BIT_DEPTH 10 not working

### ISSUE THREAD

**Issue by Ichunjo** [ultravideo/kvazaar#281]
Hello!

I'm trying to compile the master branch and I get an error when I set `KVZ_BIT_DEPTH` to 10.
I'm using Visual Studio 2015.

```
Error	C4133	'function' : incompatible types - of 'kvz_pixel [4096]' at 'uint8_t *'	 kvazaar_lib	C:\Users\Administrator\Documents\kvazaar\src\search.c	966	
```

If `KVZ_BIT_DEPTH` is 8, it's fine though.

**Comment by Arizer** [comment]
Thanks for reporting. There seems to be several problems of this kind. Will be fixed probably during the next week. We should add automated tests for this.

**Comment by moptim** [comment]
Fixed this and added a Gitlab test for the 10-bit build, to keep us more careful in the future :)

**Comment by Arizer** [comment]
Have you tried deleting old files and making a fresh build?
