### ISSUE TITLE
KVA coredump when preset=medium/slow/...

### ISSUE THREAD

**Issue by lmmRGB** [ultravideo/kvazaar#284]
Hi all,
I pulled the latest master branch code and built it, and when i tested the kvazaar with below cmd i got coredump~
version:
Kvazaar v2.0.0-5-gfaf5cc8 2020-06-25
Kvazaar license: LGPL version 2
cmd:./kvazaar -i ./kvazaar/talk_1920x1080_30.yuv --preset medium -o tmp.hevc
Machine: CentOS Linux release 7.2.1511 (Core) 
               32 core Intel(R) Xeon(R) Silver 4110 CPU @ 2.10GHz
If the preset is fast or smaller than fast, it's ok, coredump happened when the preset is medium or bigger than medium; 
So i traced the code and i found in function kvz_strategy_register_ipol(in file strategies-ipol.c) if i commented this part: "**if (kvz_g_hardware_flags.intel_flags.avx2)..**", it worked, coredump disappeared~ 
So anyone can tell me how to use the medium preset with the AVX2 correctly? Thanks~

**Comment by Arizer** [comment]
Hi,

This is probably related to issue #278

**Comment by lmmRGB** [comment]
Thanks, i got it~
 



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Ari Lemmetti"<notifications@github.com&gt;; 
发送时间: 2020年9月9日(星期三) 下午5:00
收件人: "ultravideo/kvazaar"<kvazaar@noreply.github.com&gt;; 
抄送: "木十水"<109425625@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [ultravideo/kvazaar] KVA coredump when preset=medium/slow/... (#284)





 
Hi,
 
This is probably related to issue #278
