### ISSUE TITLE
How to get RoI.txt or RoI map from video? 

### ISSUE THREAD

**Issue by Abhijeet241093** [ultravideo/kvazaar#288]
Hello Sir,

Thank you so much for your careful attention to the question.

How to get RoI.txt or RoI map from video? 

Kindly answer it.

**Comment by fador** [comment]
Hi,

The roi.txt must be generated by some other program (or manually), we only provide the interface to input it to Kvazaar.

**Comment by Abhijeet241093** [comment]
Dear Sir,

I got ROI parameter such as Detected :  504 2128 defaultdict(<class 'int'>, {504: 2127, 502: 0}).

But, I am wanted to know how to set up the QP parameter. Since there is no specific information available for that? 

ROI= <504 2128> means 504 row and 2027 column?
