### ISSUE TITLE
How to used Crypto features:: usage?

### ISSUE THREAD

**Issue by Abhijeet241093** [ultravideo/kvazaar#289]
--crypto <string>      : Selective encryption. Crypto support must be
                               enabled at compile-time. Can be 'on' or 'off' or
                               a list of features separated with a '+'. [off]
                                   - on: Enable all encryption features.
                                   - off: Disable selective encryption.
                                   - mvs: Motion vector magnitudes.
                                   - mv_signs: Motion vector signs.
                                   - trans_coeffs: Coefficient magnitudes.
                                   - trans_coeff_signs: Coefficient signs.
                                   - intra_pred_modes: Intra prediction modes.
      --key <string>         : Encryption key [16,213,27,56,255,127,242,112,
                                               97,126,197,204,25,59,38,30]
When to used it?

kvazaar --input test.yuv --input-res 3840x2160 -o test.hvc --tiles 3x3 --slices tiles --mv-constraint frametilemargin --bitrate 128000 --period 30 --input-fps 30 --crypto mv_signs?

or 

./configure --with-cryptopp mvs mv_signs trans_coeffs trans_coeff_signs?

Kindly explain its usage?

**Comment by fador** [comment]
Hi,

You only need to put those crypto parameters to Kvazaar.
`./configure --with-cryptopp` is enough to get the crypto support compiled.

so the parameter you have used should encrypt the motion vector signs, making the video look broken in normal video player. Only the OpenHEVC with correct parameters will show the result normally.
