### ISSUE TITLE
What is the size of default coding tree unit?

### ISSUE THREAD

**Issue by kjtseng** [ultravideo/kvazaar#305]
Hello,
Thanks for this awesome production.
I want to know what the size of default coding tree unit is .
Can I change it ?

**Comment by Arizer** [comment]
Hi,

Kvazaar uses 64x64 CTUs. The size is not configurable.

There was a similar issue recently that might be interesting to you: https://github.com/ultravideo/kvazaar/issues/295

**Comment by kjtseng** [comment]
> Hi,
> 
> Kvazaar uses 64x64 CTUs. The size is not configurable.
> 
> There was a similar issue recently that might be interesting to you: #295

Thank you.
