### ISSUE TITLE
Cropping the specified tile to a smaller one

### ISSUE THREAD

**Issue by RoyE3BBB** [ultravideo/kvazaar#306]
by using the code '--tile 3x3' can crop the video into tiles, but the size of each tile is completely the same(height and width).
so i wonder, can i crop the video to several different and irregular tiles, like their width are iw/4, iw/4, iw/2.

**Comment by fador** [comment]
Hi,

You should be able to do that with `--tiles-width-split` and  `--tiles-height-split`

Something like `--tiles-width-split=640,768 --tiles-height-split=256,640` where the listed numbers are pixel positions of the tile split, they have to be multiples of 64 and I think there might be some other limitations too..
