### ISSUE TITLE
Live streaming with kvazaar - low quality

### ISSUE THREAD

**Issue by laidactienbn** [ultravideo/kvazaar#307]
Hello,

I am trying to do a live streaming project with kvazaar. I am using gpac, ffmpeg and libkvazaar for gpac on MacOS BigSur.

The code I use to generate mpd segment from computer camera using gpac and encoding by kvazaar:

`gpac -i video://:fmt=avfoundation:dev="0" enc:c=libkvazaar:bitrate=1m:input-res=1920x1080:input-fps=30:fintra=1:rc::kvazaar-params=tiles=3x3,slices=tiles,mv-constraint=frametilemargin @ tilesplit @ -o /Users/tienld/Desktop/Demo_video_streaming/live.mpd:dmode=dynamic`

and after that stream with mp4client of gpac:
`mp4client /Users/tienld/Desktop/Demo_video_streaming/live.mpd`

When using this code, the result will look like this:
![image](https://user-images.githubusercontent.com/74363562/129310052-51896cb9-dd6c-43b3-a450-07d486aa45ff.png)

I tried using only gpac with no encoding:
`gpac -i video://:fmt=avfoundation:dev="0" -o /Users/tienld/Desktop/Demo_video_streaming/live.mpd:dmode=dynamic`

The result:
![image](https://user-images.githubusercontent.com/74363562/129310251-6f71a1e2-d6fd-4331-b84a-c80c5462934d.png)

Therefore, I think this has some problems with kvazaar. Does anyone know how to improve the quality of the video?

Thank you.

**Comment by laidactienbn** [comment]
Also, I have tried to remove tiling options with the following code but it stay the same as with tiling options:

`gpac -i video://:fmt=avfoundation:dev="0" enc:c=libkvazaar:bitrate=1m:fintra=1:rc:input-res=1080x720:input-fps=30 -o /Users/tienld/Desktop/Demo_video_streaming/live.mpd:dmode=dynamic`

**Comment by Jovasa** [comment]
`bitrate=1m` Kvazaar does not currently support prefixed bitrates so you are effectively setting the bitrate to 1 bit per second. Try `bitrate=1000000`, but even then 1000kbps might be too little for good quality fullHD stream.

**Comment by laidactienbn** [comment]
> `bitrate=1m` Kvazaar does not currently support prefixed bitrates so you are effectively setting the bitrate to 1 bit per second. Try `bitrate=1000000`, but even then 1000kbps might be too little for good quality fullHD stream.
Hello,
Thank you for your response.
I want to ask that what number of bitrate would be suitable for fullHD stream?

**Comment by Jovasa** [comment]
It heavily depends on content but I'd try around 3000kbps for 1080p30fps or 10Mbps if you want all-intra coding, and adjust from there based on your content and quality threshold.

**Comment by laidactienbn** [comment]
I tried with 12Mbps but it is still look like 1Mbps

**Comment by laidactienbn** [comment]
> It heavily depends on content but I'd try around 3000kbps for 1080p30fps or 10Mbps if you want all-intra coding, and adjust from there based on your content and quality threshold.

Hello Jovasa,

I have tried a lot of test cases of bitrates and fps. Also, I use my laptop camera and there is nothing wrong with the output from gpac. However, the quality is still very low. Is there any problem with the input resolution? What should I try now?

Thank you.

**Comment by Jovasa** [comment]
One thing I can thing of is to try to pass the bitrate directly to Kvazaar instead, so something like `enc:c=libkvazaar:input-res=1920x1080:input-fps=30:fintra=1::kvazaar-params=tiles=3x3,slices=tiles,mv-constraint=frametilemargin,bitrate=12000000` I'd guess. Keep in mind that I'm not really familiar with GPAC so the above command might not work

**Comment by laidactienbn** [comment]
Thank you very much. I moved input-fps to kvazaar-params and it works.
`gpac -i video://:fmt=avfoundation:dev="0" enc:c=libkvazaar:input-res=1280x720:bitrate=2000000:fintra=1:rc::kvazaar-params=tiles=3x3,slices=tiles,mv-constraint=frametilemargin,input-fps=30 @ tilesplit @ -o /Users/tienld/Desktop/Demo_video_streaming/live.mpd:dmode=dynamic`
