### ISSUE TITLE
CU coordinate identification

### ISSUE THREAD

**Issue by instrol** [ultravideo/kvazaar#312]
Hello. I am a student working on kvazaar.

I'm trying to identify the coordinates of a coding unit in "src/strategies/avx2/encode_coding_tree-avx2.c" during research, but I can't seem to get it to work.

Are there any variables or methods to identify them?

**Comment by fador** [comment]
Hi!

I don't see a way to get the info without modifying the code and adding the parameters.
You would have to modify these places and add the parameters you need:
[AVX2 version](/ultravideo/kvazaar/blob/master/src/strategies/avx2/encode_coding_tree-avx2.c#L249) + [Header](/ultravideo/kvazaar/blob/master/src/strategies/avx2/encode_coding_tree-avx2.h#L44)
[Generic version](/ultravideo/kvazaar/blob/master/src/strategies/generic/encode_coding_tree-generic.c#L40) + [Header](/ultravideo/kvazaar/blob/master/src/strategies/generic/encode_coding_tree-generic.h#L44)
[Function pointer](/ultravideo/kvazaar/blob/master/src/strategies/strategies-encode.h#L49)
and the places where it's used like [1](/ultravideo/kvazaar/blob/master/src/encode_coding_tree.c#L139) [2](/ultravideo/kvazaar/blob/master/src/encode_coding_tree.c#L175) [3](/ultravideo/kvazaar/blob/master/src/encode_coding_tree.c#L179) [4](/ultravideo/kvazaar/blob/master/src/rdo.c#L266)

I hope this helps!

Best Regards,
Marko

**Comment by instrol** [comment]
Thank you for your comments.
Actually, I've done encryption at the tile level. 
I want to perform encryption in CU units. I know that video processing is done by CU. This seems to be possible.
However, although I restricted the scope of the encryption via the abs_x variable, the encryption seems to tend to be broadcast. 
Specifically, in "kvz_encode_mvd", I restricted the "MV sign" encryption feature through the x, y(CU-coordinate) parameter setting, but it didn't work well. 

Is there a good way to encrypt at the CU level?

Thank you for your attetion.

Best Regards,
Yong

**Comment by instrol** [comment]
> Best Regards,

and then, i tried to follow the instructions you gave me. But that code doesn't work well. Can you give me a concrete example or how to do it? My ultimate goal is to identify the values of abs_x, abs_y in the "kvz_encode_coeff_nxn_avx2" function. please answer about my question.
