### ISSUE TITLE
all-i mode

### ISSUE THREAD

**Issue by clorislili** [ultravideo/kvazaar#317]
hi
if I would like to convert y4m to all-i mode hevc, then I can set '-p 1' to realize all-i mode right?

**Comment by fador** [comment]
Hi,

Yes, setting `-p 1` will make the encoder use "All-Intra" mode with all of the frames coded in I-mode.

**Comment by clorislili** [comment]
> 

And is compress an image file with all-i mode equal to compress the image in the file one by one? The latter one means a video consists a single image in the file

**Comment by fador** [comment]
Yes it should be, but we only add parameter sets one time at the beginning by default. If you want to be closer to coding single images you can set `--vps-period 1` so it will add the parameters also for each video frame..
