### ISSUE TITLE
`test_slices` fails to pass

### ISSUE THREAD

**Issue by dbermond** [ultravideo/kvazaar#319]
I'm getting the following test failure with kvazaar git master:

```
PASS: kvazaar_tests
XFAIL: test_external_symbols.sh
PASS: test_invalid_input.sh
PASS: test_interlace.sh
PASS: test_rate_control.sh
PASS: test_mv_constraint.sh
PASS: test_intra.sh
FAIL: test_slices.sh
PASS: test_smp.sh
PASS: test_weird_shapes.sh
PASS: test_tools.sh
PASS: test_owf_wpp_tiles.sh
PASS: test_pu_depth_constraints.sh
PASS: test_gop.sh
============================================================================
Testsuite summary for kvazaar 2.1.0
============================================================================
# TOTAL: 14
# PASS:  12
# SKIP:  0
# XFAIL: 1
# FAIL:  1
# XPASS: 0
# ERROR: 0
```

`test_slices` is failing, and `test_slices.sh.log` shows:

```
$ TAppDecoderStatic -b /tmp/tmp.khm2dFJOmG
./util.sh: line 16: 10287 Aborted                 (core dumped) "$@"
FAIL test_slices.sh (exit status: 134)
```

Full content of [test_slices.sh.log](https://github.com/ultravideo/kvazaar/files/8210014/test_slices.sh.log).

When manually running the command that is giving segmentation fault, it shows:

```
$ ffmpeg -f lavfi -i mandelbrot=size=264x130 -vframes 10 -pix_fmt yuv420p -f yuv4mpegpipe tmp.j06PYorTf7
$ libtool execute path/to/src/kvazaar -i tmp.j06PYorTf7 --input-res=264x130 -o tmp.khm2dFJOmG --threads=2 --owf=1 --preset=ultrafast --slices=wpp
$ TAppDecoderStatic -b tmp.khm2dFJOmG

HM software: Decoder Version [16.24] (including RExt)[Linux][GCC 11.1.0][64 bit] 
/usr/include/c++/11.1.0/bits/stl_vector.h:1045: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](std::vector<_Tp, _Alloc>::size_type) [with _Tp = unsigned char; _Alloc = std::allocator<unsigned char>; std::vector<_Tp, _Alloc>::reference = unsigned char&; std::vector<_Tp, _Alloc>::size_type = long unsigned int]: Assertion '__n < this->size()' failed.
Aborted (core dumped)
```

I tried to change a lot of things, like disabling LTO, disabling all compiler and linker flags, disabling crypto++, using ffmpeg 4.4.1, using HM git master, etc. Nothing works, same result.

Curiously, the tests were passing fine a while ago. The system got a toolchain bump: glibc 2.33 -> 2.35, binutils 2.36 -> 2.38 and gcc 11.1.0 -> 11.2.0. The tests were passing fine at the time of glibc 2.33.

System: Arch Linux x86_64
Compiler: gcc 11.2.0
Yasm: 1.3.0
ffmpeg: 5.0
HM: 16.24

**Comment by fador** [comment]
Thank you for reporting this!
We'll try to figure out why it's failing, but we are quite busy with other projects right now so don't expect fast answer ;)

**Comment by dbermond** [comment]
Thank you for the reply.

**Comment by antonio-rojas** [comment]
> Curiously, the tests were passing fine a while ago. The system got a toolchain bump: glibc 2.33 -> 2.35, binutils 2.36 -> 2.38 and gcc 11.1.0 -> 11.2.0. The tests were passing fine at the time of glibc 2.33.

This is because hm has been built with GLIBCXX_ASSERTIONS. It works fine with `hm 16.24-1`. or if you rebuild hm with `CXXFLAGS+=" -Wp,-U_GLIBCXX_ASSERTIONS"`

**Comment by dbermond** [comment]
Oh yes, glibc assertions macro. Should have figured it out for myself earlier.

Thank you @antonio-rojas, nice catch :)

Closing.
