### ISSUE TITLE
Reasons for smearing crypto feature "KVZ_CRYPTO_TRANSF_COEFF_SIGNS"?

### ISSUE THREAD

**Issue by instrol** [ultravideo/kvazaar#320]
Dear kvazaar developers and members

First, thank you for your last comments. We tried CU based encryption in kvazaar by modifying the code, and the following result was obtained .

![그림1](https://user-images.githubusercontent.com/28687650/158438909-6f6f348d-a124-4567-a1e7-53da4230f586.png)

The yellow boundary is the range of the CU coordinates we set. This setting was done in "encode_coding_tree-avx2.c".
However, as you can see, the crypto feature "KVZ_CRYPTO_TRANSF_COEFF_SIGNS" is applied beyond the range we set. What are the reasons for this? Any advice would be greatly appreciated.

**Comment by Jovasa** [comment]
It is not that the `KVZ_CRYPTO_TRANSF_COEFF_SIGNS` is applied beyond the designated area but the fact that intra prediction copies pixels from the left and/or right edges of the CU. If you want to contain the distortion to the designated area you'll have to make sure that the CUs to the right and bottom of the area do not copy data from the encrypted area. The easiest way would be to use the DC mode (mode 1), which does not copy pixel data from, for the surrounding CUs, however, this will have a negative effect to the encoding efficiency.

**Comment by instrol** [comment]
Thank you very much for your comment.
However, we have a few questions left.

1. What process or modification is required to use DC mode (mode 1)?

2. In the picture above, we set the crypto feature to "KVZ_CRYPTO_INTRA_MODE = 0". Does this have anything to do with your comment?

3. The picture above used the tiling function. The left boundary area spans the tile. There is no problem in applying the crypto feature in the upper tile, but does the problem occur in the lower tile?

please answer about my question.
thank you.

**Comment by Jovasa** [comment]
1. The easiest choice would be to change https://github.com/ultravideo/kvazaar/blob/6918ab80aee031d736e029186f8ccc687f85647c/src/search_intra.c#L898 in `kvz_search_cu_intra` to set the best mode to DC when right or bottom to the encrypted area. I think the `x_px` and `y_px` coordinates in that function are relative to the tile the PU is located in. It is probably a good idea to also set the cost to the cost of the DC mode instead of whatever is the actual best mode, though this is not strictly necessary.
2. No.
3. The encryption cannot `spill` across tile borders in all intra encoding. The reason that the upper tile is fine is that you got lucky and none of the surrounding intra modes copy data from the encrypted area.

**Comment by instrol** [comment]
Thank you for your detailed and kind comments.
Many questions have been answered by your comment.

thank you.

**Comment by instrol** [comment]
I have an additional question, so I reopened it like this.
Based on the advice you gave before, we have mitigated some issues with crypto feature "KVZ_CRYPTO_TRANSF_COEFF_SIGNS" via DC mode (mode 1).

![그림4](https://user-images.githubusercontent.com/28687650/161508592-8bdc8e87-f500-4d9f-ada8-f811e85e41ac.png)

However, as shown in the picture, when the crypto feature "KVZ_CRYPTO_TRANSF_COEFF_SIGNS" was applied, it was confirmed that the crypto feature was applied beyond the range specified by me on the x-axis. The red line is the boudary of the y-axis tile, the yellow line is the range of crypto features that I have specified, and the green line is the range where the actual crypto features are applied.

For the left side, the crypto feature has never exceeded the specified range, and for the right side only, the crypto feature is applied until it meets the boundary of the tile. I understand some of these properties, but haven't been able to find a way to fix them.

I would really appreciate it if you could reply to this.
thank you.

**Comment by Jovasa** [comment]
Can you show the exact implementation of forcing the DC mode and the command line you are using?

**Comment by instrol** [comment]
I forced DC mode as below in "search_intra.c" file.
` *mode_out = modes[1];` >>> end line of "search_intra.c" file.

 And I am using these commands.
"kvazaar -i threeman.yuv --preset=ultrafast --input-res 1280x720 --tiles 6x3 --crypto=intra_pred_modes+mvs+mv_signs+trans_coeffs+trans_coeff_signs --key 16,213,27,56,255,127,242,112,97,126,197,204,25,59,38,30 --mv-constraint=frametilemargin -o threeman_intra.hevc"

However, here, except for the crypto feature "KVZ_CRYPTO_TRANSF_COEFF_SIGNS", I set all crypto features to "0" in the "kvazaar.h" file as shown below.
`enum kvz_crypto_features {
  KVZ_CRYPTO_OFF = 0,
  KVZ_CRYPTO_MVs = 0, //(1 << 0),
  KVZ_CRYPTO_MV_SIGNS = 0, //(1 << 1),
  KVZ_CRYPTO_TRANSF_COEFFS = 0, //(1 << 2),
  KVZ_CRYPTO_TRANSF_COEFF_SIGNS = (1 << 3),
  KVZ_CRYPTO_INTRA_MODE = 0, //(1 << 4),
  KVZ_CRYPTO_ON = (1 << 5) - 1,
};`

**Comment by Jovasa** [comment]
Sorry for not getting back to you earlier, I have been preoccupied with other issues.

I should have double checked, and actually DC does use the surrounding pixels. What you need to do is to restrict the intra mode between 2-10 for the CUs directly below the encrypted area, and 26-35 directly right of the encrypted area.

**Comment by instrol** [comment]
Thank you for your comments. 

It sounds like you need to modify the function "kvz_search_cu_intra" in "search_intra.c", how can I restrict it?

Thank you always for your hard work.

**Comment by Jovasa** [comment]
`*mode_out = modes[2-10];` There is no concept of "range" in C, that's just a plain old subtraction and you end up indexing the `modes` array with `-8`. Secondly there is no guarantee that the index of the `modes` array corresponds to the mode number. 

You'll need to check if the x_px coordinate is directly right of the encrypted area. I have no idea how and where you store the information about the encrypted area, thus it is somewhat hard to give accurate help. But something like this pseudo-code. It is probably easier to start if you force the encoder to use single size pus, e.g. `--pu-depth-intra 3-3 --no-combine-intra` will force the encoder to use only 8x8 intra pus.
```C
if(inside_encypted(x_xp - 1) && ! inside_encypted(x_xp) && inside_encypted(y_xp)){
  *mode_out = 26;
}
else if (inside_encypted(y_xp - 1) && ! inside_encypted(y_xp) && inside_encypted(x_xp) {
  *mode_out = 10;
}
else {
  *mode_out = modes[best_mode_i];
}
```

**Comment by instrol** [comment]
Thanks a lot for the advice.

Your advice has improved me even further.
I'll try again based on your advice.

thank you.
