### ISSUE TITLE
Wrong encoded

### ISSUE THREAD

**Issue by wojxhr** [ultravideo/kvazaar#322]
Hi,
I download an avc1 video and using ffmpeg to trans it into hevc.
`ffmpeg -i 2-4-FemaleBasketball.mp4 -vcodec libx265 FemaleBasketball.mp4`
![2022-03-30 19-57-25 的屏幕截图](https://user-images.githubusercontent.com/43904172/160831078-87449c7a-e154-4d7a-b1fe-31cb3d4842f4.png)
Then I use kvazaar to encode it.
`kvazaar -i FemalBasketball.mp4 --input-res 3840x1920 -o 600k.hvc --tiles 6x6 --slices tiles --mv-constraint frametilemargin --bitrate 600000 --period 30 --input-fps 30`
It seems that something wrong happened.
![kvazaar](https://user-images.githubusercontent.com/43904172/160827986-5f34d7ac-65a0-4ca2-96a6-786c25d126cb.png)
Then I user MP4Box to generate the MPD file.
`MP4Box -add 600k.hvc:split_tiles -fps 30 -new video_tiled.mp4`
`MP4Box -dash 1000 -rap -frag-rap -profile live -out dash_tiled.mpd video_tiled.mp4`
![MPD](https://user-images.githubusercontent.com/43904172/160828118-dea54836-cdbf-4025-9680-8ff449c3bc73.png)
The video should have 6:01.33 duration.And the MPD file only has 1 period and the duration is 0.266s.
I'm new to this,could you please help me?

**Comment by Jovasa** [comment]
Kvazaar requires YUV420 rawvideo as input. You are now trying to re-encode the binary that ffmpeg produces. You'll either want to pipe the ffmpeg output to kvazaar or use kvazaar directly inside ffmpeg. If piping `ffmpeg -i 2-4-FemaleBasketball.mp4 -f rawvideo -pix_fmt yuv420p - | kvazaar -i - --input-res 3840x1920 -o 600k.hvc --tiles 6x6 --slices tiles --mv-constraint frametilemargin --bitrate 600000 --period 30 --input-fps 30`. For ffmpeg inegration you might want to take a look at this issue https://github.com/ultravideo/kvazaar/issues/277 

Just a side note but 600000 bitrate is very low bitrate for 3840x1920 video you'll want to try something that is at least a magnitude higher.

**Comment by wojxhr** [comment]
It's very kind of you! Thanks for help!
