### ISSUE TITLE
About tile size manipulation

### ISSUE THREAD

**Issue by instrol** [ultravideo/kvazaar#327]
Hello. Thank you always for your kind replies.
Actually, I was curious about the tile function, so I asked this question.
Any reply would be really appreciated. 

1. Currently, kvazaar automatically size the tile when we enter the row and column of the tile. Can the user manipulate the size of the tiles themselves? If possible, how?

2. Based on 1280x720 resolution, how many rows and how many columns can be tiled? Splitting more than a certain level gave the result that it doesn't work.

3. If question 1 is possible, can we change the size of the tile every frame?, will it affect the encoding efficiency a lot?

Thanks for reading.

**Comment by fador** [comment]
Hi,

1. you can do it with `--tiles-width-split` and `--tiles-height-split`, e.g. `--tiles-width-split=640,768 --tiles-height-split=256,640` would split the video in 3x3 tiles. Splits are done in the specified pixel coordinates, but they must be multiples of 64.
2. If I remember corretly, the width of the tile has to be 256 and the height can be 64, so I think `--tiles 5x12` might work for 1280x720.
3.  Changing the tile configuration is not supported by Kvazaar and I'm not sure if even the HEVC specification allows it.

**Comment by Jovasa** [comment]
To extend on fador's comments:
2. I'm pretty sure minimum height is 128 pixels 
3. HEVC spec allows changing the tile size for each frame, but changing Kvazaar to support it would most likely require months of work.

**Comment by instrol** [comment]
Thank you very much for the members' comments.

The comments helped me out in clearing my doubts.

Thank you
