### ISSUE TITLE
About encryption time measurement

### ISSUE THREAD

**Issue by instrol** [ultravideo/kvazaar#329]
Hello. I have an additional question, so I've created a new issue.

I want to measure encryption time.
Several functions are under consideration, but I want to know precisely what function should be encrypted.
Which function's operating time should be measured?

Please answer my question.
Thank you.

**Comment by Jovasa** [comment]
Realistically the encryption time is so minuscule that it has no measurable difference in the whole encoding process. The best way would be to measure the whole encoding time with and without the encryption but again you will have more difference from just noise than the effect of encryption. 

If you really care about function level I'd start with the functions in `crypto.cpp` and once that have `_encry` or `_encryption` suffix.

**Comment by instrol** [comment]
Thank you for your detailed comments.

There are various functions related to encryption in crypto.cpp. I calculated the execution time from line 80 to the end. When the test was performed with a video called "vidyo1" with a resolution of 1280 x 720 and 600 frames, it took 3.035 seconds in full-frame encryption.

Does this fit your envisioned encryption time? Or is it too long?
If my measurement method is strange, please advise.

thank you.
