### ISSUE TITLE
question of slice function

### ISSUE THREAD

**Issue by instrol** [ultravideo/kvazaar#331]
I have a question about the slice function.

1. As shown in the figure below, when a video is splited through the slice function, is it possible to independently encode some CTUs included in the slice?

For example, is it possible to encrypt only slices 6 and 7 of Slice #1? No impact on other CTUs

2. Using kvazaar's function, we want to divide the slice as shown in the picture. What command do we need?

![image](https://user-images.githubusercontent.com/28687650/173365657-07ee6f18-c54a-4c68-b352-9451e1fba44c.png)

Thank you for your reply.

**Comment by Jovasa** [comment]
Kvazaar only supports setting slices as WPP rows, tiles, or both. And even if it supported your proposed solution the slices here would be dependent of each other.

**Comment by instrol** [comment]
thank you for the reply.
