### ISSUE TITLE
Question about setting the number of tiles

### ISSUE THREAD

**Issue by instrol** [ultravideo/kvazaar#332]
hello. Thank you for your kind comments as always.

After trying various things, a question came up, so I'm asking this question.
When we try to encode 3840x2160 resolution video by parallel processing into tiles, it is said that it is split horizontally up to a maximum of 47 tiles. But considering the minimum size of tiles (64x64), it should be possible up to 60, so why is there a limit?

And unconditionally increasing the number of tiles does not help to improve efficiency. Is there an optimized number of tiles for each resolution?

please answer about my question.
thank you

**Comment by Jovasa** [comment]
Just FYI the HEVC Main profile restricts the width of tiles to minimum 256, although some decoders will still happily decode the compressed video.

Annex A.3.2 of the standard
> When an active PPS for the base layer has tiles_enabled_flag equal to 1, 
ColumnWidthInLumaSamples[ i ] shall be greater than or equal to 256 for all values of i in the range 
of 0 to num_tile_columns_minus1, inclusive, and RowHeightInLumaSamples[ j ] shall be greater than 
or equal to 64 for all values of j in the range of 0 to num_tile_rows_minus1, inclusive.

**Comment by instrol** [comment]
thank you Your comments have been very helpful.
