### ISSUE TITLE
default setting: For one video there is only one PPS，could every frame have one PPS?

### ISSUE THREAD

**Issue by haikuoY** [ultravideo/kvazaar#334]
To do the adaptive tile partition, the tile partition could change through the whole video, when tile partition is changed we need new PPS, how to achieve that? Thanks a lot!

**Comment by fador** [comment]
I think the only way currently is to set `--vps-period 1` and it will send the parameter sets again every Intra frame..

**Comment by haikuoY** [comment]
So We can not set different PPS for every Intra frame?

**Comment by haikuoY** [comment]
Thanks a lot!
