### ISSUE TITLE
If I  can change QP when encoding a video？How?

### ISSUE THREAD

**Issue by FarewellYi** [ultravideo/kvazaar#348]
We want to change qp in one Video.
For example，the video has 300 frames，and we set GOP length = 30，in this situation，the video will have 10 Closed GOP（eg. segment），and we want each segment have different QP，QP in the first is 22，in the second is 24，……， in the last segment is 42.
In order to realize this method, we improt a new parameter in options，meaning qp difference.
The issue is，after we use this new parameter and use a hevc analyzer（Zond）, only the first segment can decode successfully，the next segment, looks like below
![image](https://user-images.githubusercontent.com/47736905/191470363-073d2fec-37e9-49d9-b3dc-1748872b0149.png)

So, is there having some methods to solve this issue, or which api should be called, or some parameters be set? 

PS:our cmd line parameters as below:
--input  RaceHorses_832x480_30.yuv --input-res 832x480 --input-fps 30 --qp_diff 2 --period 30 --gop lp-g30d1t1 --output RaceHorses_gop_g30d1t1.hevc
--qp_diff is the new parameter

Looking for your reply!

**Comment by Jovasa** [comment]
It's hard to comment on what might be wrong since I have no idea what changes you have done, but if you are updating the base qp set in picture parameter set (PPS) you need to set `--vps-period 1` to resend the changed PPS with every intra frame.

**Comment by FarewellYi** [comment]
Thanks for your reply！

In fact, we add a new variable “qp_diff” in struct kva_config and others structs which are relavant, and we determines whether the number of encoded frames is an integer multiple of period, if true, we will plus qp_diff to encoder‘s config qp.
So, we didn't change a lot of code, and I guess the reason may be what your reply. I will try as soon as possible.

Btw, except for what you mentioned, do you have another advices?

**Comment by Jovasa** [comment]
Incrementing the qp field of encoder config will not work when owf is enabled, instead you should set the `state->frame->QP` correctly in `kvz_set_picture_lambda_and_qp`.

**Comment by FarewellYi** [comment]
Wow, the speed with which you responded was amazing!

And thank for your advice, i will do it soon.

If there are still any questions, I hope to get your reply again!

**Comment by FarewellYi** [comment]
And，i tried with this parameters：
--input  RaceHorses_832x480_30.yuv --input-res 832x480 --input-fps 24 --qp_diff 2 --no-open-gop --period 24 --threads 0 --owf 0 --output RaceHorses.hevc
the second IDR frame will look like this：
![image](https://user-images.githubusercontent.com/47736905/191491658-ba42eb00-fd75-4b28-a043-e8c00edcf134.png)

**Comment by Jovasa** [comment]
To me that looks like that the encoder and decoder are using different QPs

**Comment by FarewellYi** [comment]
After several testing, we found this parameter set was useful:

--input RaceHorses_416x240_30.yuv --input-res 416x240 --input-fps 30 --period 30 --vps-period 1 --ref 1 --qp_diff 2 --gop lp-g30d1t1 --no-open-gop --owf 0 --output RaceHorses.hevc 

The hevc streaming analysis result looks like below:
![image](https://user-images.githubusercontent.com/47736905/191651439-fa2d6319-87ed-408a-8e2e-929f092e62bb.png)

Thank for your help. Hope you have a nice day!

**Comment by PercyLau** [comment]
Greetings! This issue seems that there is a simple way to support somewhat variable bitrate mode for kvazaar. @FarewellYi Perhaps we could discuss more in detail.
