### ISSUE TITLE
Realtime encoding blur

### ISSUE THREAD

**Issue by pinbraerts** [ultravideo/kvazaar#363]
![image](https://github.com/ultravideo/kvazaar/assets/23105717/9d459cc8-97b9-49b7-b70d-3989e7e01af5)

- Input file: https://media.xiph.org/ldv/pub/test_sequences/720p/720p5994_stockholm_ter.yuv
- Visual Studio 2019 (Retargeted the solution to v142 build tools)
- Release
- x64
- kvazaar_cli
- any preset
- additional parameters: `-i 720p5994_stockholm_ter.yuv --bitrate 2000000 --period 300 --input-res 1280x720 --input-fps 5994/100 --ref 1 --gop lp-g1d1t1 --no-bipred --owf 0`

psnr Y drops down to 24

Minimal encoding without b-frames. `--owf 1` solves the problem but adds one frame delay.
The most interesting part is that problem takes place only at bitrates from ~1390000 to ~3900000
You could even bisect to unstable bifurcation bitrates [1398310-3933034] in my case

**Comment by Jovasa** [comment]
Does `--intra-bits false` or `--rc-algorithm oba` help with the issue?  Otherwise, I'll look more into this tomorrow or next week. The gop length of 1 can also cause some issues. Also I'm very confused why increasing the `owf` from 0 to 1 would improve the situation, when it has been so far always the opposite, where owf 0 fixes most rate control issues.

**Comment by fador** [comment]
Very interesting, it just keeps increasing the QP (decreasing quality) towards the end.
I can confirm that if you change the rate-control algorithm `--rc-algorithm oba` or add `--no-intra-bits` it works just fine.

**Comment by pinbraerts** [comment]
`--no-intra-bits` doesn't solve the issue by itself
`--rc-algorithm oba` does, but it's 3 times slower than default in cli (5 times slower in the field)
Other videos with the same movement do not cause similar problems at different bitrates.
Sitting here: [master/e001c6a](https://github.com/ultravideo/kvazaar/commit/e001c6a867068b448354d955363bd2ff7caf33d2)

**Comment by Jovasa** [comment]
Fixed with aab6aa9b349d2768f9371ef58680298c200e47e6

**Comment by pinbraerts** [comment]
Just tested. Thank you very much for your fast reply and fix!
