### ISSUE TITLE
build error in visual studio 2022

### ISSUE THREAD

**Issue by raposeidon** [ultravideo/kvazaar#369]
My tool version is
**Microsoft Visual Studio Community 2022 (64-bit) - Current
version 17.7.2**

To change properties as below image.
https://user-images.githubusercontent.com/48763518/60673758-13c84900-9eab-11e9-8908-90423eebc866.png

but compiler shows error message.
MSB3721	""C:\Program Files\Microsoft Visual Studio\2022\Community\VC\bin\"vsyasm.exe -Xvc -f x64 -i "D:\Dev\OpenSourceLib\kvazaar\build\..\src\strategies\x86_asm" -i "D:\Dev\OpenSourceLib\kvazaar\build\..\src\extras" -i "D:\Dev\OpenSourceLib\kvazaar\build\..\src\strategies\x86_asm" -d "ARCH_X86_64=1" -d "HAVE_ALIGNED_STACK=1" -o "x64-Debug\\" -rnasm -pnasm   "..\\..\\src\strategies\x86_asm\picture-x86-asm-sad.asm"" 명령이 종료되었습니다(코드: 1).	kvazaar_lib	D:\Dev\OpenSourceLib\kvazaar\build\yasm\vsyasm.targets	45	

somebody help me.

**Comment by fador** [comment]
Hi,
It seems that you don't have vsyasm.exe available, since it's not part of visual studio and you have to download it separately. You can get it from http://yasm.tortall.net/Download.html and we also have it hosted in https://ultravideo.fi/vsyasm.exe . Add it to any directory that is in %PATH% (C:\Program Files\Microsoft Visual Studio\2022\Community\VC\bin should also work) and try recompiling.

**Comment by raposeidon** [comment]
@fador 
The files "picture-x86-asm-sad.obj" and "picture-x86-asm-satd.obj" are generated in the "src\strategies\x86_asm" directory. However, even when including the "src\strategies\x86_asm" folder in the project, it was not being recognized, leading to the issue. As a solution, I copied the aforementioned two files to the "\kvazaar\build\kvazaar_lib\x64-Debug" folder, which enabled the successful build.

Thank you.

**Comment by raposeidon** [comment]
when release build, kvazaar_cli project error occurred.

D:\Dev\OpenSourceLib\kvazaar\src\strategies\avx2\intra-avx2.c(127): fatal error C1001: An internal compiler error has occurred.
(Compiler file 'D:\a\_work\1\s\src\vctools\Compiler\Utc\src\p2\main.c', line 234)
To resolve this issue, simplify or modify the program near the location listed above.
If possible, reproduce the problem at https://developercommunity.visualstudio.com.
For more details, choose [Technical Support] from the Visual C++ Help menu or refer to the technical support help file.

link!RaiseException()+0x6c
link!RaiseException()+0x6c
link!InvokeCompilerPassW()+0x8a967
link!InvokeCompilerPass()+0x1ad9e3
link!InvokeCompilerPass()+0x1c6d39
link!InvokeCompilerPass()+0x1b0360
link!InvokeCompilerPass()+0x1c7dcf

D:\Dev\OpenSourceLib\kvazaar\src\strategies\avx2\intra-avx2.c(127) is
static void filter_8x8_avx2(uint8_t *dst, const uint8_t *ref_main, int sample_disp, bool vertical_mode){.

**Comment by raposeidon** [comment]
ha~~~

https://stackoverflow.com/questions/38266085/how-do-i-workaround-error-c1001-in-visual-c-compiler/63435683#63435683
