### ISSUE TITLE
Buildig project failed 

### ISSUE THREAD

**Issue by jamesrech** [ultravideo/kvazaar#375]
I am experiencing a problem with building kvazaar using Visual Studio,  I thought it was the version I already installed that has the issue, so I tried to install the new one from the github  "https://github.com/ultravideo/kvazaar/" and build it using Visual studio but still I am getting the same issue below is the error it generated when I try to build it using visual studio.

(Severity	Code Description Project File	Line	Suppression State Error MSB3721 The command "vsyasm.exe -Xvc -f win64 -i "E:\kvazaar.git\trunk\build\..\src\extras" -i "E:\kvazaar.git\trunk\build\..\src\extras" -i "E:\kvazaar.git\trunk\build\..\src\strategies\x86-asm" -d "ARCH_X86_64=1" -d "HAVE_ALIGNED_STACK=1" -o "x64-Release\\" -rnasm -pnasm   "..\..\src\strategies\x86_asm\picture-x86-asm-sad.asm"  "..\..\src\strategies\x86_asm\picture-x86-asm-satd.asm"" exited with code 1. kvazaar_lib	E:\kvazaar.git\trunk\build\yasm\vsyasm.targets 4)

**Comment by Jovasa** [comment]
Do you have vsyasm in your PATH? See: https://github.com/ultravideo/kvazaar/issues/324#issuecomment-1103729824

**Comment by jamesrech** [comment]
Yes I have the vyasm , it is located in the same path in the folder "yasm" see the path below
E:\Kvazaar.git folder\trunk\build\yasm

**Comment by jamesrech** [comment]
yes

**Comment by jamesrech** [comment]
I actually I was using it properly it has just started recently

**Comment by Jovasa** [comment]
Which version of visual studio you are using? The version number can be found from Help -> About Microsoft Visual Studio

**Comment by jamesrech** [comment]
I am using Version 16.11.30

**Comment by Jovasa** [comment]
As of v2.3.0 yasm is no longer used and this should no longer be an issue
