### ISSUE TITLE
A Solution for build problem with VS2022

### ISSUE THREAD

**Issue by raposeidon** [ultravideo/kvazaar#380]
LNK1181	'x64-Debug\picture-x86-asm-sad.obj': No such file or directory

Yasm assembler configuration is incorrect.
Change 'x86-asm' to 'x86_asm' in Include Paths.
Add the following command to the command line of the pre-link event:
`copy /Y $(SolutionDir)..\src\strategies\x86_asm\*.obj $(IntDirfullPath)`

Please apply this solution.

Yasm 어셈블러 구성이 잘못되었습니다. 
Include Paths에서 "x86-asm"을 "x86_asm"로 변경합니다.
링크 전 이벤트의 명령줄에 다음 명령어를 추가하십시오.
`copy /Y $(SolutionDir)..\src\strategies\x86_asm\*.obj $(IntDirfullPath)`

이 해결책을 반영하여 주십시오.

**Comment by Jovasa** [comment]
As of v2.3.0 yasm is no longer used and this should no longer be an issue
