### ISSUE TITLE
Problem with AVX2 SIMD

### ISSUE THREAD

**Issue by Jamaika1** [ultravideo/kvazaar#409]
When do I use SIMD AVX then codec works.
When do I use SIMD AVX2 then codec doesn't work.

**Compiled: INTEL, flags: MMX SSE SSE2 SSE3 SSSE3 SSE41 SSE42 ???**
Detected: INTEL, flags: MMX SSE SSE2 SSE3 SSSE3 SSE41 SSE42 AVX AVX2
Available: avx2(5)
In use: avx2(5)
--owf=auto value set to 3.
--threads=auto value set to 20.
Output #0, matroska, to 'output_kvazaar.mkv':
Metadata:
major_brand : isom
minor_version : 512
compatible_brands: isomiso2avc1mp41
encoder : Lavf61.5.101
Stream #0:0(und): Video: hevc, 1 reference frame, yuv420p(progressive, left), 1920x1080 [SAR 1:1 DAR 16:9], q=2-31, 3000 kb/s, 29.97 fps, 1k tbn (default)
Metadata:
handler_name : VideoHandler
vendor_id : [0][0][0][0]
encoder : Lavc61.10.100 libkvazaar
Stream #0:1(und): Audio: aac (LC) ([255][0][0][0] / 0x00FF), 48000 Hz, stereo, fltp, delay 1024, 128 kb/s (default)
Metadata:
handler_name : SoundHandler
vendor_id : [0][0][0][0]
encoder : Lavc61.10.100 aac
[out#0/matroska @ 000001e63341b2c0] Starting thread...
```Assertion failed: cur_cu->type != CU_NOTSET, file ../../src/search.c, line 1044its/s speed= 0.6x```

**Comment by Jovasa** [comment]
Hello, could you please provide some additional information, for example:
- What is the used version of Kvazaar?
- Compiler?
- Were some non-default compile flags used?
- Build system?
- Used CPU?
- Operating system?
- You appear to be using kvazaar in FFmpeg? What is the used version?
- What are the options provided for Kvazaar?

**Comment by Jamaika1** [comment]
https://forum.doom9.org/showthread.php?p=2004554#post2004554

**Comment by Jovasa** [comment]
Yeah, that does not really, help. I can see that you are using FFmpeg 7.1.0 (what is this even? the latest FFmpeg release is 7.0.1), compiled with GCC 11.3.1, but this is not nearly enough that I could start to debug where the issue is.

**Comment by Jamaika1** [comment]
https://github.com/FFmpeg/FFmpeg/releases/tag/n7.1-dev
