### ISSUE TITLE
Shared and static libraries

### ISSUE THREAD

**Issue by darealshinji** [ultravideo/kvazaar#89]
Building shared and static libraries is very easy. This could be useful for projects like ffmpeg. However, I don't know how often the ABI changes and shared library with an ABI version in the SONAME is important on Unix systems.
I think this might be worth adding to the build system.

Building a static library:
``` sh
make
rm -f interface_main.o
ar cru libkvazaar.a $(find . -name \*.o | tr '\n' ' ')
ranlib libkvazaar.a
```

Shared library:
``` sh
CFLAGS=-fPIC make
rm -f interface_main.o
gcc -shared -Wl,-soname,libkvazaar.so.0 $(find . -name \*.o | tr '\n' ' ')\
 -lrt -lm -pthread -o libkvazaar.so.0
```

Test the shared library:
``` sh
rm -f kvazaar
ln -s libkvazaar.so.0 libkvazaar.so
make interface_main.o
gcc interface_main.o -L. -lkvazaar -lrt -lm -pthread -o kvazaar
LD_PRELOAD=./libkvazaar.so ./kvazaar
```

**Comment by aryla** [comment]
The Makefile now has rules for building shared and static libraries.
