### ISSUE TITLE
Recommended cmd parameters to achieve the best coding effciency

### ISSUE THREAD

**Issue by WeiXiao126** [ultravideo/kvazaar#92]
Hi, I wonder the best coding efficiency kvazaar v0.4 can achieve? Can its coding efficiency close to the HM encoder?
If the cmd line as following can achieve the best coding efficiency(with full RDO, sub ME and full intra search)?
--rd 2 --subme 1 --full-intra-search

**Comment by Venti-** [comment]
For intra coding I think --rd=2 is sufficient to get close to HM in RD performance. Full intra search should only bring a tiny benefit while slowing down the encoding a lot, so I wouldn't recommend using that.

For inter coding, Kvazaar is still missing B-frames, asymmetric motion partitions and some other stuff, so it will not get close to any configuration of HM that is using those features. For best RD performance possible right now though, use --rd=2 and --subme=1.

**Comment by WeiXiao126** [comment]
Thank you for your reply! For inter lowdelay P (IPPP) configuration, are the existing tools also not sufficient to close to HM?

**Comment by Venti-** [comment]
I did a quick test with two small sequences (BQMall_832x480 and RaceHorses_416x240) between HM encoder_lowdelay_P_main.cfg and Kvazaar --rd=2. HM had a bdrate of -43% and -35% respectively while being about 4 times slower. Thats a greater difference than I was expecting, but not that suprising considering how little work has been put into RD performance of inter coding in Kvazaar.

I think -40% is about the same as HM had over H.264 High Profile in low delay P, although I'm sure we will catch up as we begin to focus more on inter coding.

**Comment by WeiXiao126** [comment]
Thank you! My test shows the same result with yours. And I find that using --rd=2 and default parameter (I think it is --rd=0) show the similar coding efficiency for lowdelay_P_main configuration. Looking forward to your next version!

**Comment by Venti-** [comment]
The default are --rd=1 and --subme=1. There used to be a bigger difference between rd 1 and 2 but it makes sense that it would be similar now.

May I ask what is your interest in Kvazaar? Just curious.

**Comment by WeiXiao126** [comment]
I am more interested in inter coding optimization than intra as the video coding usually uses inter configurations in real applications. One professor mentioned Kvazaar for your efforts in encoder optimization, and I started to know your work.

**Comment by Venti-** [comment]
Ok, thanks.
