### ISSUE TITLE
-fpic breaks compilation on MingW

### ISSUE THREAD

**Issue by wiiaboo** [ultravideo/kvazaar#96]
https://github.com/ultravideo/kvazaar/commit/af2b417809652f08e5be4243e9863db1e82c6122 broke compilation on MingW because of `-fpic` and `-Werror`.

On compilation for Windows targets (afaik), `-fpic` is always ignored by GCC and since you also added `-Werror` every warning gets turned into an error. Either removing `-Werror` or `-fpic` from the Makefile fixes it.

**Comment by Venti-** [comment]
Ok. It probably doesn't make sense to compile the executables with fpic anyway, so I'm going to see if I can tweak the makefile to avoid that, and not use fpic on windows.

**Comment by Venti-** [comment]
54b1be3 fixes this issue. Thanks for letting us know.
